### PR TITLE
fix: use --platform opt when pulling containers

### LINKED ISSUE #406: Container with wrong platform pulled
## What did you expect to happen?

topgrade should update/pull all docker images for the proper platform.

In https://github.com/topgrade-rs/topgrade/blob/master/src/steps/containers.rs there should also the platform for the container be determined and added to the docker pull call with option "--platform", see https://docs.docker.com/engine/reference/commandline/pull/.

## What actually happened?

When topgrade processes the "containers" steps and uses docker pull to download/update the image it did not specify the --platform parameter to pull the proper image.

I have images on my Mac M1 multipass Ubuntu vm for platform linux/arm64 (linux/aarch64) and linux/amd64 (linux/86_64) but topgrade always pulls linux/arm64 images no matter if this is right.

I have these images on my machine:

```shell
Multipass~Ubuntu-22.04> [ssh] ubuntu@MBP:~$ .config/topgrade-docker-pull --list
Docker default platform: linux/arm64 (linux/aarch64)

REPOSITORY:TAG                                       PLATFORM     CREATED
grafana/oncall:latest                                linux/arm64  2023-04-19T16:08:40.849901636Z
portainer/portainer-ce:latest                        linux/arm64  2023-04-18T03:39:48.003125532Z
redis:latest                                         linux/arm64  2023-04-17T22:43:33.190112885Z
localhost/webserver:latest                           linux/arm64  2023-04-14T12:41:59.404768251+02:00
quay.io/prometheusmsteams/prometheus-msteams:latest  linux/amd64  2023-04-07T15:26:12.950797626Z
prom/prometheus:latest                               linux/arm64  2023-03-21T13:39:06.125286225Z
grafana/grafana:latest                               linux/arm64  2023-03-17T00:06:13.178743487Z
prom/alertmanager:latest                             linux/arm64  2022-12-22T15:18:01.508240991Z
```

One is linux/amd64 all others are linux/arm64 and when I use topgrade to update the containers it fails for the amd64 image because this one did not have a arm64 image available:

```shell
Multipass~Ubuntu-22.04> [ssh] ubuntu@MBP:~$ topgrade --only containers
Due to a design issue with notify-send it could be that topgrade hangs when it's finished.
If this is the case on your system add the --skip-notify flag to the topgrade command or set skip_notify = true in the config file.
If you don't want this message to appear any longer set display_preamble = false in the config file.
For more information about this issue see https://askubuntu.com/questions/110969/notify-send-ignores-timeout and https://github.com/topgrade-rs/topgrade/issues/288.

── 11:18:04 - Self update ──────────────────────────────────────────────────────
Topgrade is up-to-date

── 11:18:04 - Containers ───────────────────────────────────────────────────────
latest: Pulling from grafana/oncall
Digest: sha256:c2c03166d69d5a0bd69807128c2f1d245fa29a164fb8e29563906add8b3fa2e8
Status: Image is up to date for grafana/oncall:latest
docker.io/grafana/oncall:latest
latest: Pulling from portainer/portainer-ce
Digest: sha256:45104bb2ecbc7c24de937b4c43f87b85c9c7dd46924d27203c2aa2a613f78322
Status: Image is up to date for portainer/portainer-ce:latest
docker.io/portainer/portainer-ce:latest
latest: Pulling from library/redis
Digest: sha256:f50031a49f41e493087fb95f96fdb3523bb25dcf6a3f0b07c588ad3cdbe1d0aa
Status: Image is up to date for redis:latest
docker.io/library/redis:latest
latest: Pulling from prometheusmsteams/prometheus-msteams
no matching manifest for linux/arm64/v8 in the manifest list entries
ERROR Pulling container 'quay.io/prometheusmsteams/prometheus-msteams:latest' failed: Command failed: `/usr/bin/docker pull quay.io/prometheusmsteams/prometheus-msteams:latest`
latest: Pulling from prom/prometheus
Digest: sha256:f5c29683a301d4e5427fb0d985f794b1f743498310a4eadee75e85f5dba73a6d
Status: Image is up to date for prom/prometheus:latest
docker.io/prom/prometheus:latest
latest: Pulling from grafana/grafana
Digest: sha256:1a359d92f40ef98049b1aac3e43cb4a569f5dc0e552caa883a6b6f4ae1eacded
Status: Image is up to date for grafana/grafana:latest
docker.io/grafana/grafana:latest
latest: Pulling from prom/alertmanager
Digest: sha256:fd4d9a3dd1fd0125108417be21be917f19cc76262347086509a0d43f29b80e98
Status: Image is up to date for prom/alertmanager:latest
docker.io/prom/alertmanager:latest
Total reclaimed space: 0B

── 11:18:22 - Summary ──────────────────────────────────────────────────────────
Containers: FAILED


Multipass~Ubuntu-22.04> [ssh] ubuntu@MBP:~$  docker image inspect quay.io/prometheusmsteams/prometheus-msteams:latest | jq -r '.[] | "\(.Os)/\(.Architecture)"'
linux/amd64

Multipass~Ubuntu-22.04> [ssh] ubuntu@MBP:~$ docker system info --format '{{.OSType}}/{{.Architecture}}'
linux/aarch64
```

## Additional Details
- Which operating system or Linux distribution are you using?

```shell
Multipass~Ubuntu-22.04> [ssh] ubuntu@MBP:~$ uname -a
Linux MBP-009 5.15.0-70-generic #77-Ubuntu SMP Tue Mar 21 15:58:51 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

Multipass~Ubuntu-22.04> [ssh] ubuntu@MBP:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```

- How did you install Topgrade?

From github releases assets once and self update afterwards

- Which version are you running? 

```shell
Multipass~Ubuntu-22.04> [ssh] ubuntu@MBP:~$ topgrade -V
Topgrade 10.3.3
```

- Workaround

I disabled step containers and added a custom script to do this:

```shell
#!/usr/bin/env bash
docker_default_platform=$(docker system info --format '{{.OSType}}/{{.Architecture}}')
docker_default_platform_normalized=$(echo $docker_default_platform | \
  sed -e 's/aarch64/arm64/' -e 's/armhf/arm/' -e 's/armel/arm\/v6/' -e 's/i386/386/' -e 's/x86[_-]64/amd64/')

echo "Docker default platform: $docker_default_platform_normalized ($docker_default_platform)"
echo

unset header
for i in $(docker image list --format '{{.Repository}}:{{.Tag}}' | grep -v '<none>'); do
  image_json=$(docker image inspect "$i")
  image_platform=$(echo "$image_json" | jq -r '.[] | "\(.Os)/\(.Architecture)"')
  [[ "$*" == *"--foreign"* && "$image_platform" == "$docker_default_platform_normalized" ]] && continue

  if [[ "$*" == *"--list"* ]]; then
    if [[ -z "$header" ]]; then
      printf "REPOSITORY:TAG\tPLATFORM\tCREATED\tSIZE/BYTES\tIMAGE ID\n"
      header=1
    fi
    printf "%s\t%s\n" "$i" \
      "$(echo "$image_json" | jq -r '.[] | "\(.Os)/\(.Architecture)\t\(.Created)\t\(.Size)\t\(.Id)"')"
  else
    printf "\033[0;34m%s\033[0m (\033[0;36m%s\033[0m)%s\n" \
      "$i" \
      "$(echo "$image_json" | jq -r '.[] | "\(.Os)/\(.Architecture)"')" \
      "$(echo "$image_json" | jq -r '.[] | ", created \(.Created), \(.Size) Bytes"')"
    if [[ "$i" == "localhost"* ]]; then
      echo "Skipping local created image"
      echo
      continue
    fi
    docker pull --platform "$image_platform" "$i"
    echo
  fi
done | if [[ "$*" != *"--list"* ]] ; then cat ; else column -t -s $'\t'; fi
```

<details>

<pre>

</pre>
</details>

### PR DESCRIPTION
**Pull request by SteveLauC**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The code compiles (`cargo build`)
- [x] The code passes rustfmt (`cargo fmt`)
- [x] The code passes clippy (`cargo clippy`)
- [x] The code passes tests (`cargo test`)
- [x] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

-----
Closes #406 

See [this comment](https://github.com/topgrade-rs/topgrade/issues/406#issuecomment-1558508725) for what the root cause is and how this patch works
```shell
$ docker image ls
REPOSITORY   TAG       IMAGE ID       CREATED       SIZE
alpine       latest    44dd6f223004   13 days ago   7.73MB

$ docker image inspect 44 --format '{{.Os}}/{{.Architecture}}'
linux/arm64

$ uname -m 
x86_64

# With this patch
$ ./target/debug/topgrade --only containers

── 12:45:56 - Containers ───────────────────────────────────────────────────────
latest: Pulling from library/alpine
Digest: sha256:02bb6f428431fbc2809c5d1b41eab5a68350194fb508869a33cb1af4444c9b11
Status: Image is up to date for alpine:latest
docker.io/library/alpine:latest

── 12:45:59 - Summary ──────────────────────────────────────────────────────────
Containers: OK

$ docker image ls
REPOSITORY   TAG       IMAGE ID       CREATED       SIZE
alpine       latest    44dd6f223004   13 days ago   7.73MB

$ docker image inspect 44 --format '{{.Os}}/{{.Architecture}}'
linux/arm64
```

### CODE REVIEW

File: src/steps/containers.rs [hunk 1]
```diff
@@ -18,15 +19,42 @@ use crate::{execution_context::ExecutionContext, utils::require};
 // themselves or when using docker-compose.
 const NONEXISTENT_REPO: &str = "repository does not exist";
 
+/// Uniquely identifies a `Container`.
+#[derive(Debug)]
+struct Container {
```
Comment (SteveLauC) [inline src/steps/containers.rs:24]: This type technically should be named `Image`,  but let's call it `Container` as this is what `topgrade` currently uses

**Review by DottoDev — APPROVED** [review]
