### PR TITLE
Fixes dotnet if dotnet tool is not available

### LINKED ISSUE #225: Dotnet update fails
## What did you expect to happen?
Updating Dotnet if necessary

## What actually happened?
The update command fails

## Additional Details
- Which operating system or Linux distribution are you using?
Manjaro Linux 22
- How did you install Topgrade?
Tested fresh extraction of topgrade-v10.2.0-x86_64-unknown-linux-gnu.tar.gz and selfupdate of topgrade
- Which version are you running? 
Topgrade 10.2.0

Got this error
.NET failed: 
   0: Command failed: `/usr/bin/dotnet tool list --global`

      Stderr:
      The command could not be loaded, possibly because:
        * You intended to execute a .NET application:
            The application 'tool' does not exist.
        * You intended to execute a .NET SDK command:
            No .NET SDKs were found.

      Download a .NET SDK:
      https://aka.ms/dotnet/download

      Learn about SDK resolution:
      https://aka.ms/dotnet/sdk-not-found
   1: `/usr/bin/dotnet` failed: exit status: 145

Location:
   src/steps/generic.rs:455

<details>

<pre>
DEBUG Step ".NET"
DEBUG Detected "/usr/bin/dotnet" as "dotnet"
DEBUG Executing command `/usr/bin/dotnet tool list --global`
DEBUG Command failed: Err(
   0: Command failed: `/usr/bin/dotnet tool list --global`

      Stderr:
      The command could not be loaded, possibly because:
        * You intended to execute a .NET application:
            The application 'tool' does not exist.
        * You intended to execute a .NET SDK command:
            No .NET SDKs were found.

      Download a .NET SDK:
      https://aka.ms/dotnet/download

      Learn about SDK resolution:
      https://aka.ms/dotnet/sdk-not-found
   1: `/usr/bin/dotnet` failed: exit status: 145

Location:
   src/steps/generic.rs:455

</pre>
</details>
Hello,

the problem seems to be this the command dotnet tool list is part of dotnet SDK and is not included in Dotnet runtime, see https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-list

Btw the dotnet update step was ok in topgrade 10.1.2

### LINKED ISSUE #269: .NET failed
Running Topgrade 10.2.2 on Arch based distros that are fully updated 

## Full system update without a Topgrade error

##It gets to .NET and it fail.

~~~
╰─λ topgrade -v
DEBUG Configuration at /home/locutus/.config/topgrade.toml
DEBUG Loaded configuration: ConfigFile { pre_sudo: None, pre_commands: Some({}), post_commands: None, commands: Some({}), git_repos: None, predefined_git_repos: None, disable: Some([Emacs, Distrobox]), ignore_failures: None,remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, git_arguments: None, tmux_arguments: None, set_title: None, display_time: None, assume_yes: None, yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, no_retry: None, run_in_tmux: None, cleanup: None, notify_each_step: None, accept_all_windows_updates: None, skip_notify: None, bashit_branch: None, only: None, composer: Some(Composer { self_update: None }), brew: Some(Brew { greedy_cask: None, autoremove: None }), linux: Some(Linux { yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, arch_package_manager: None, show_arch_news: None, trizen_arguments: None, pikaur_arguments: None, pamac_arguments: None, dnf_arguments: None, apt_arguments: None, enable_tlmgr: None, redhat_distro_sync: None, rpm_ostree: None, emerge_sync_flags: None, emerge_update_flags: None }), git:Some(Git { max_concurrency: None, arguments: None, repos: None, pull_predefined: None }), windows: Some(Windows{ accept_all_updates: None, self_rename: None, open_remotes_in_new_terminal: None, enable_winget: None }), npm:Some(NPM { use_sudo: None }), yarn: None, vim: None, firmware: Some(Firmware { upgrade: None }), vagrant: None,flatpak: Some(Flatpak { use_sudo: None }), distrobox: None }
DEBUG Detected "/usr/bin/notify-send" as "notify-send"
DEBUG Version: 10.2.2
DEBUG OS: x86_64-unknown-linux-gnu
DEBUG Args { inner: ["topgrade", "-v"] }
DEBUG Binary path: Ok("/usr/bin/topgrade")
DEBUG Self Update: false
DEBUG Detected "/usr/bin/git" as "git"
DEBUG Cannot find "doas"
DEBUG Detected "/usr/bin/sudo" as "sudo"
DEBUG Cannot find "pwsh"
DEBUG Cannot find "powershell"
DEBUG Step "System update"

―― 07:32:42 - System update ――――――――――――――――――――――――――――――――――――――――――――――――――――
DEBUG Cannot find "powerpill"
DEBUG Detected "/usr/bin/garuda-update" as "garuda-update"
DEBUG Executing command `/usr/bin/garuda-update`
[sudo] password for locutus:
:: Synchronizing package databases...
garuda is up to date
core is up to date
extra is up to date
community is up to date
multilib is up to date
chaotic-aur is up to date
arcolinux_repo                         137.2 KiB   311 KiB/s 00:00 [-------------------------------------] 100%
arcolinux_repo_3party                  313.8 KiB   902 KiB/s 00:00 [-------------------------------------] 100%
arcolinux_repo_xlarge                   37.7 KiB  1047 KiB/s 00:00 [-------------------------------------] 100%
nemesis_repo is up to date
endeavouros is up to date
xerolinux_repo is up to date
xerolinux_repo_xl is up to date

--> Refreshing mirrorlists using rate-mirrors, please be patient..
:: Synchronizing package databases...
garuda                                  96.7 KiB   204 KiB/s 00:00 [-------------------------------------] 100%
core                                   152.5 KiB   641 KiB/s 00:00 [-------------------------------------] 100%
extra                                 1728.3 KiB  4.14 MiB/s 00:00 [-------------------------------------] 100%
community                                7.2 MiB  4.47 MiB/s 00:02 [-------------------------------------] 100%
multilib                               163.0 KiB   580 KiB/s 00:00 [-------------------------------------] 100%
chaotic-aur                              2.2 MiB  3.86 MiB/s 00:01 [-------------------------------------] 100%
arcolinux_repo                         137.2 KiB   927 KiB/s 00:00 [-------------------------------------] 100%
arcolinux_repo_3party                  313.8 KiB  5.47 MiB/s 00:00 [-------------------------------------] 100%
arcolinux_repo_xlarge                   37.7 KiB  1508 KiB/s 00:00 [-------------------------------------] 100%
nemesis_repo                             2.3 KiB  24.6 KiB/s 00:00 [-------------------------------------] 100%
endeavouros                             32.4 KiB  24.0 KiB/s 00:01 [-------------------------------------] 100%
xerolinux_repo                          88.0 KiB  79.5 KiB/s 00:01 [-------------------------------------] 100%
xerolinux_repo_xl                        6.8 KiB  10.9 KiB/s 00:01 [-------------------------------------] 100%
spawn pacman -Su
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (6) lib32-libnm-1.40.8-1  libnm-1.40.8-1  networkmanager-1.40.8-1  nm-cloud-setup-1.40.8-1
samba-4.17.4-1  smbclient-4.17.4-1

Total Download Size:    20.03 MiB
Total Installed Size:  111.80 MiB
Net Upgrade Size:        0.11 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
libnm-1.40.8-1-x86_64                 1126.7 KiB   790 KiB/s 00:01 [-------------------------------------] 100%
nm-cloud-setup-1.40.8-1-x86_64          50.6 KiB  1100 KiB/s 00:00 [-------------------------------------] 100%
lib32-libnm-1.40.8-1-x86_64            448.9 KiB   267 KiB/s 00:02 [-------------------------------------] 100%
samba-4.17.4-1-x86_64                    8.2 MiB  3.77 MiB/s 00:02 [-------------------------------------] 100%
networkmanager-1.40.8-1-x86_64           3.5 MiB  1399 KiB/s 00:03 [-------------------------------------] 100%
smbclient-4.17.4-1-x86_64                6.7 MiB  1568 KiB/s 00:04 [-------------------------------------] 100%
Total (6/6)                             20.0 MiB  4.52 MiB/s 00:04 [-------------------------------------] 100%
(6/6) checking keys in keyring                                      [-------------------------------------] 100%
(6/6) checking package integrity                                    [-------------------------------------] 100%
(6/6) loading package files                                         [-------------------------------------] 100%
(6/6) checking for file conflicts                                   [-------------------------------------] 100%
(6/6) checking available disk space                                 [-------------------------------------] 100%
:: Running pre-transaction hooks...
(1/1) Creating Timeshift snapshot before upgrade...
Using system disk as snapshot device for creating snapshots in BTRFS mode
Mounted '/dev/nvme0n1p4' at '/run/timeshift/230641/backup'
E: ERROR: can't list qgroups: quotas not enabled

E: btrfs returned an error: 256
E: Failed to query subvolume quota
Creating new backup...(BTRFS)
Saving to device: /dev/nvme0n1p4, mounted at path: /run/timeshift/230641/backup
Created directory: /run/timeshift/230641/backup/timeshift-btrfs/snapshots/2022-12-16_07-34-55
Created subvolume snapshot: /run/timeshift/230641/backup/timeshift-btrfs/snapshots/2022-12-16_07-34-55/@
Created control file: /run/timeshift/230641/backup/timeshift-btrfs/snapshots/2022-12-16_07-34-55/info.json
BTRFS Snapshot saved successfully (0s)
Tagged snapshot '2022-12-16_07-34-55': ondemand
------------------------------------------------------------------------------
Mounted '/dev/nvme0n1p4' at '/run/timeshift/230775/backup'
E: ERROR: can't list qgroups: quotas not enabled

E: btrfs returned an error: 256
E: Failed to query subvolume quota
------------------------------------------------------------------------------
Removing snapshot: 2022-12-16_05-09-21
Deleting subvolume: @ (Id:706)
Deleted subvolume: @ (Id:706)

Deleted directory: /run/timeshift/230775/backup/timeshift-btrfs/snapshots/2022-12-16_05-09-21
Removed snapshot: 2022-12-16_05-09-21
------------------------------------------------------------------------------
:: Processing package changes...
(1/6) upgrading libnm                                               [-------------------------------------] 100%
(2/6) upgrading lib32-libnm                                         [-------------------------------------] 100%
(3/6) upgrading networkmanager                                      [-------------------------------------] 100%
(4/6) upgrading nm-cloud-setup                                      [-------------------------------------] 100%
(5/6) upgrading smbclient                                           [-------------------------------------] 100%
(6/6) upgrading samba                                               [-------------------------------------] 100%
:: Running post-transaction hooks...
(1/9) Reloading system manager configuration...
(2/9) Creating temporary files...
(3/9) Reloading device manager configuration...
(4/9) Arming ConditionNeedsUpdate...
(5/9) Foreign/AUR package notification
flaresolverr-bin 2.2.10-1
freefilesync-bin 11.28-1
komga 0.157.5-1
lib32-openssl-1.0 1.0.2.u-2
libcpuid-git 2:0.6.2.r0.g3d1ed27-1
metis 5.1.0.p10-2
openssl-1.0 1.0.2.u-1
radarr-develop 4.3.1.6822-1
renamemytvseries-qt-bin 2.1.8-1
searchmonkey-gtk 0.8.3-2
smtube 21.10.0-4
sonarr-develop 4.0.0.287-1
vdhcoapp-bin 1.6.3-1
yad-git 9267829-1
(6/9) Orphaned package notification...
afdko 3.9.1-1.1
alpm_octopi_utils 1.0.2-3.2
asciidoc 10.2.0-2
asp 8-1
aspnet-runtime 7.0.1.sdk101-1
black-hole-solver 1.12.0-1
cabextract 1.9.1-2
debugedit 5.0-4
devtools 20221012-2
doxygen 1.9.5-1
fontforge 20220308-1
freecell-solver 6.8.0-1
fvs 0.3.4-1.1
gambas3-dev-tools 3.17.3-8
gambas3-gb-desktop 3.17.3-8
gambas3-gb-desktop-x11 3.17.3-8
gambas3-gb-form 3.17.3-8
geocode-glib 3.26.4-2
glew1.10 1.10.0-3
gnome-desktop 1:43-1
gnugo 3.8-7
gspell 1.12.0-2
gtksourceview3 1:3.24.11+r28+g73e57b57-1
gtksourceview5 5.6.1-1
icoextract 0.1.4-1.1
inotify-tools 3.22.6.0-1
itstool 1:2.0.7-1
kplotting 5.101.0-1
ksnakeduel 22.12.0-1
ksquares 22.12.0-1
lib32-alsa-oss 1.1.8-3
lib32-dbus-glib 0.112-2
lib32-glew1.10 1.10.0-5
lib32-gsm 1.0.22-1
lib32-libappindicator-gtk2 12.10.0-13
lib32-libcaca 0.99.beta20-1
lib32-libcurl-compat 7.86.0-2
lib32-libcurl-gnutls 7.86.0-2
lib32-libgcrypt15 1.5.6-7
lib32-libgudev 237-2
lib32-libidn11 1.33-2
lib32-libjpeg6-turbo 1.5.3-2
lib32-libnm 1.40.8-1
lib32-libpng12 1.2.59-2
lib32-librtmp0 2.4-4
lib32-libsoup 2.74.3-1
lib32-libtheora 1.1.1-13
lib32-libtiff4 3.9.7-5
lib32-libudev0-shim 1-5
lib32-libvdpau 1.5-1
lib32-libvpx 1.12.0-2
lib32-libvpx1.3 1.3.0-3
lib32-libwrap 7.6.31-4
lib32-libxss 1.2.3-2
lib32-lzo 2.10-2
lib32-openssl-1.0 1.0.2.u-2
lib32-openssl-1.1 1.1.1.s-1
lib32-rust-libs 1:1.66.0-1
lib32-sdl2_image 2.6.2-1
lib32-sdl2_mixer 2.6.2-1
lib32-sdl2_ttf 2.20.1-1
lib32-sdl_image 1.2.12-7
lib32-sdl_mixer 1.2.12-5
lib32-sdl_ttf 2.0.11-6
lib32-smpeg 2.0.0-1
libgcrypt15 1.5.6-6
libidn11 1.33-2
libjpeg6-turbo 1.5.3-2
libktorrent 22.12.0-1
libpng12 1.2.59-2
libportal-gtk4 0.6-1
libretro-beetle-pce 1147-1
libretro-beetle-pce-fast 1193-1
libretro-beetle-psx 2637-1
libretro-beetle-psx-hw 2637-1
libretro-beetle-supergrafx 959-1
libretro-blastem 2052-2
libretro-bsnes 1:3075-1
libretro-bsnes-hd 51-1
libretro-bsnes2014 1:577-2
libretro-citra 9294-2
libretro-desmume 6349-1
libretro-dolphin 33038-1
libretro-duckstation 2105-2
libretro-flycast 5247-1
libretro-gambatte 977-1
libretro-genesis-plus-gx 1957-1
libretro-kronos 7016-2
libretro-melonds 2010-1
libretro-mesen 2903-2
libretro-mesen-s 916-3
libretro-mgba 8702-1
libretro-mupen64plus-next 1:440-1
libretro-nestopia 1:93-1
libretro-parallel-n64 5243-1
libretro-picodrive 2252-1
libretro-play 7461-1
libretro-ppsspp 34704-1
libretro-retrodream 1104-2
libretro-sameboy 1720-2
libretro-scummvm 93205-2
libretro-snes9x 2168-1
libretro-stella2014-git 294.1351a4f-1
libretro-yabause 3340-2
librtmp0 2.4-5
libtiff4 3.9.7-5
libvpx1.3 1.3.0-3
lld 14.0.6-1
love 11.4-1
meson 0.64.1-1
metis 5.1.0.p10-2
mingw-w64-gcc 12.2.0-1
mingw-w64-tools 10.0.0-1
nasm 2.15.05-1
patool 1.12-5.1
python-build 0.9.0-1
python-installer 0.6.0-1
python-pytest 7.2.0-4
python-scikit-build 0.16.3-1
python-send2trash 1.8.0-3
python-setuptools-scm 7.0.5-1
python-steamgriddb 1.0.5-1.1
python-vdf 3.4-2.1
python-zeroconf 0.39.4-1
qgpgme 1.18.0-1
qtermwidget 1.2.0-1
rest 0.8.1+r4+ge5ee6ef-1
retroarch-assets-glui 1:439-1
sdl2_ttf 2.20.1-1
sdl_net 1.2.8-5
sdl_sound 1.0.3-11
smtube 21.10.0-4
timidity++ 2.15.0-9
vala 0.56.3-1
wayland-protocols 1.31-1
wine-gecko 2.47.3-1
wine-mono 7.4.0-1
wine-nine 0.8-3
wineasio 1.1.0-7
xorg-server-xvfb 21.1.5-1
zenity 3.43.0-1
(7/9) Checking for .pacnew and .pacsave files...
(8/9) Reloading system bus configuration...
(9/9) Syncing all file systems...

Checking for plugin updates
Nothing to install / update

System updated! 🐧
DEBUG Step "config-update"
DEBUG Detected "/usr/bin/pacdiff" as "pacdiff"
DEBUG Detected "/usr/bin/vim" as "vim"

―― 07:34:59 - Configuration update ―――――――――――――――――――――――――――――――――――――――――――――
DEBUG Executing command `/usr/bin/sudo '--preserve-env=DIFFPROG' /usr/bin/pacdiff`
DEBUG Step "Brew"
DEBUG Step "yadm"
DEBUG Step "nix"
DEBUG Step "guix"
DEBUG Step "home-manager"
DEBUG Step "asdf"
DEBUG Step "pkgin"
DEBUG Step "bun"
DEBUG Path "/home/locutus/.config/emacs" doesn't exist
DEBUG Path "/home/locutus/.emacs.d" doesn't exist
DEBUG /home/locutus/.vim does not exists
DEBUG /home/locutus/.config/nvim does not exists
DEBUG /home/locutus/.ideavimrc does not exists
DEBUG /home/locutus/.intellimacs does not exists
DEBUG /home/locutus/.dotfiles does not exists
DEBUG /home/locutus/.zshrc is a file. Checking /home/locutus
DEBUG Checking if /home/locutus is a git repository
DEBUG Executing command `/usr/bin/git rev-parse --show-toplevel`
DEBUG Command failed: Err(
0: Command failed: `/usr/bin/git rev-parse --show-toplevel`

Stderr:
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
1: `/usr/bin/git` failed: exit status: 128

Location:
src/steps/git.rs:167

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.)
DEBUG /home/locutus/.tmux does not exists
DEBUG Checking if /home/locutus/.config/fish is a git repository
DEBUG Executing command `/usr/bin/git rev-parse --show-toplevel`
DEBUG Command failed: Err(
0: Command failed: `/usr/bin/git rev-parse --show-toplevel`

Stderr:
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
1: `/usr/bin/git` failed: exit status: 128

Location:
src/steps/git.rs:167

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.)
DEBUG /home/locutus/.config/openbox does not exists
DEBUG /home/locutus/.config/bspwm does not exists
DEBUG /home/locutus/.config/i3 does not exists
DEBUG /home/locutus/.config/sway does not exists
DEBUG Step "Git repositories"
DEBUG Step "zr"
DEBUG Detected "/usr/bin/zsh" as "zsh"
DEBUG Step "antibody"
DEBUG Detected "/usr/bin/zsh" as "zsh"
DEBUG Step "antigen"
DEBUG Detected "/usr/bin/zsh" as "zsh"
DEBUG Path "/home/locutus/.zshrc" exists
DEBUG Step "zgenom"
DEBUG Detected "/usr/bin/zsh" as "zsh"
DEBUG Path "/home/locutus/.zshrc" exists
DEBUG Step "zplug"
DEBUG Detected "/usr/bin/zsh" as "zsh"
DEBUG Path "/home/locutus/.zshrc" exists
DEBUG Step "zinit"
DEBUG Detected "/usr/bin/zsh" as "zsh"
DEBUG Path "/home/locutus/.zshrc" exists
DEBUG Step "zi"
DEBUG Detected "/usr/bin/zsh" as "zsh"
DEBUG Path "/home/locutus/.zshrc" exists
DEBUG Step "zim"
DEBUG Detected "/usr/bin/zsh" as "zsh"
DEBUG Executing command `zsh -c '[[ -n ${ZIM_HOME} ]] && print -n ${ZIM_HOME}'`
DEBUG Command failed: Err(
0: Command failed: `zsh -c '[[ -n ${ZIM_HOME} ]] && print -n ${ZIM_HOME}'`
1: `zsh` failed: exit status: 1

Location:
src/steps/zsh.rs:122

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.)
DEBUG Step "oh-my-zsh"
DEBUG Detected "/usr/bin/zsh" as "zsh"
DEBUG Path "/home/locutus/.oh-my-zsh" exists

―― 07:34:59 - oh-my-zsh ――――――――――――――――――――――――――――――――――――――――――――――――――――――――
DEBUG Executing command `zsh -c 'test $ZSH_CUSTOM && echo -n $ZSH_CUSTOM'`
DEBUG Command failed: Err(
0: Command failed: `zsh -c 'test $ZSH_CUSTOM && echo -n $ZSH_CUSTOM'`
1: `zsh` failed: exit status: 1

Location:
src/steps/zsh.rs:148

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.)
DEBUG Running zsh returned Command failed: `zsh -c 'test $ZSH_CUSTOM && echo -n $ZSH_CUSTOM'`. Using default path: /home/locutus/.oh-my-zsh/custom
DEBUG oh-my-zsh custom dir: /home/locutus/.oh-my-zsh/custom
DEBUG Checking if /home/locutus/.oh-my-zsh/custom is a git repository
DEBUG Executing command `/usr/bin/git rev-parse --show-toplevel`
DEBUG /home/locutus/.oh-my-zsh/custom/example.zsh is a file. Checking /home/locutus/.oh-my-zsh/custom
DEBUG Checking if /home/locutus/.oh-my-zsh/custom is a git repository
DEBUG Executing command `/usr/bin/git rev-parse --show-toplevel`
DEBUG Checking if /home/locutus/.oh-my-zsh/custom/plugins is a git repository
DEBUG Executing command `/usr/bin/git rev-parse --show-toplevel`
DEBUG Checking if /home/locutus/.oh-my-zsh/custom/plugins/example is a git repository
DEBUG Executing command `/usr/bin/git rev-parse --show-toplevel`
DEBUG Checking if /home/locutus/.oh-my-zsh/custom/plugins/zsh-completions is a git repository
DEBUG Executing command `/usr/bin/git rev-parse --show-toplevel`
DEBUG Checking if /home/locutus/.oh-my-zsh/custom/plugins/zsh-autosuggestions is a git repository
DEBUG Executing command `/usr/bin/git rev-parse --show-toplevel`
DEBUG Checking if /home/locutus/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting is a git repository
DEBUG Executing command `/usr/bin/git rev-parse --show-toplevel`
DEBUG Checking if /home/locutus/.oh-my-zsh/custom/themes is a git repository
DEBUG Executing command `/usr/bin/git rev-parse --show-toplevel`
DEBUG /home/locutus/.oh-my-zsh/custom/themes/example.zsh-theme is a file. Checking /home/locutus/.oh-my-zsh/custom/themes
DEBUG Checking if /home/locutus/.oh-my-zsh/custom/themes is a git repository
DEBUG Executing command `/usr/bin/git rev-parse --show-toplevel`
DEBUG Checking if /home/locutus/.oh-my-zsh/custom/themes/powerlevel10k is a git repository
DEBUG Executing command `/usr/bin/git rev-parse --show-toplevel`
Pulling custom plugins and themes
DEBUG Executing command `/usr/bin/git remote show`
DEBUG Executing command `/usr/bin/git remote show`
DEBUG Executing command `/usr/bin/git remote show`
DEBUG Executing command `/usr/bin/git remote show`
DEBUG Executing command `/usr/bin/git rev-parse HEAD`
Pulling /home/locutus/.oh-my-zsh/custom/plugins/zsh-completions
DEBUG Executing command `/usr/bin/git rev-parse HEAD`
Pulling /home/locutus/.oh-my-zsh/custom/plugins/zsh-autosuggestions
DEBUG Executing command `/usr/bin/git rev-parse HEAD`
Pulling /home/locutus/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
DEBUG Executing command `/usr/bin/git rev-parse HEAD`
Pulling /home/locutus/.oh-my-zsh/custom/themes/powerlevel10k
DEBUG Executing command `/usr/bin/git rev-parse HEAD`
Up-to-date /home/locutus/.oh-my-zsh/custom/themes/powerlevel10k
DEBUG Executing command `/usr/bin/git rev-parse HEAD`
Up-to-date /home/locutus/.oh-my-zsh/custom/plugins/zsh-autosuggestions
DEBUG Executing command `/usr/bin/git rev-parse HEAD`
Up-to-date /home/locutus/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
DEBUG Executing command `/usr/bin/git rev-parse HEAD`
Up-to-date /home/locutus/.oh-my-zsh/custom/plugins/zsh-completions
DEBUG Executing command `zsh /home/locutus/.oh-my-zsh/tools/upgrade.sh`
Updating Oh My Zsh
__                                     __
____  / /_     ____ ___  __  __   ____  _____/ /_
/ __ \/ __ \   / __ `__ \/ / / /  /_  / / ___/ __ \
/ /_/ / / / /  / / / / / / /_/ /    / /_(__  ) / / /
\____/_/ /_/  /_/ /_/ /_/\__, /    /___/____/_/ /_/
/____/

Oh My Zsh is already at the latest version.

To keep up with the latest news and updates, follow us on Twitter: https://twitter.com/ohmyzsh
Want to get involved in the community? Join our Discord: https://discord.gg/ohmyzsh
Get your Oh My Zsh swag at: https://shop.planetargon.com/collections/oh-my-zsh
DEBUG Step "fisher"
DEBUG Detected "/usr/bin/fish" as "fish"
DEBUG Executing command `/usr/bin/fish -c 'type -t fisher'`
DEBUG Command failed: Err(
0: Command failed: `/usr/bin/fish -c 'type -t fisher'`

Stderr:
type: Could not find 'fisher'
1: `/usr/bin/fish` failed: exit status: 1

Location:
src/steps/os/unix.rs:95

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.)
DEBUG Step "bash-it"
DEBUG Step "oh-my-fish"
DEBUG Detected "/usr/bin/fish" as "fish"
DEBUG Step "fish-plug"
DEBUG Detected "/usr/bin/fish" as "fish"
DEBUG Step "fundle"
DEBUG Detected "/usr/bin/fish" as "fish"
DEBUG Step "tmux"
DEBUG Step "TLDR"
DEBUG Detected "/usr/bin/tldr" as "tldr"

―― 07:35:00 - TLDR ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
DEBUG Executing command `/usr/bin/tldr --update`
Successfully updated cache.
DEBUG Step "pearl"
DEBUG Step "Gnome Shell Extensions"
DEBUG Detected "/usr/bin/gdbus" as "gdbus"
DEBUG Step "SDKMAN!"
DEBUG Detected "/usr/bin/bash" as "bash"
DEBUG Step "rcm"
DEBUG Step "apm"
DEBUG Step "fossil"
DEBUG Step "rustup"
DEBUG Detected "/home/locutus/.cargo/bin/rustup" as "rustup"

―― 07:35:00 - rustup ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
DEBUG Executing command `/home/locutus/.cargo/bin/rustup self update`
info: checking for self-updates
rustup unchanged - 1.25.1

DEBUG Executing command `/home/locutus/.cargo/bin/rustup update`
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: checking for self-updates

stable-x86_64-unknown-linux-gnu unchanged - rustc 1.66.0 (69f9c33d7 2022-12-12)

info: cleaning up downloads & tmp directories
DEBUG Step "juliaup"
DEBUG Step ".NET"
DEBUG Detected "/usr/bin/dotnet" as "dotnet"
DEBUG Executing command `/usr/bin/dotnet tool list --global`
DEBUG Command failed: Err(
0: Command failed: `/usr/bin/dotnet tool list --global`

Stderr:
The command could not be loaded, possibly because:
* You intended to execute a .NET application:
The application 'tool' does not exist.
* You intended to execute a .NET SDK command:
No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
1: `/usr/bin/dotnet` failed: exit status: 145

Location:
src/steps/generic.rs:476

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.)
DEBUG Step ".NET" failed:
0: Command failed: `/usr/bin/dotnet tool list --global`

Stderr:
The command could not be loaded, possibly because:
* You intended to execute a .NET application:
The application 'tool' does not exist.
* You intended to execute a .NET SDK command:
No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
1: `/usr/bin/dotnet` failed: exit status: 145

Location:
src/steps/generic.rs:476

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
.NET failed:
0: Command failed: `/usr/bin/dotnet tool list --global`

Stderr:
The command could not be loaded, possibly because:
* You intended to execute a .NET application:
The application 'tool' does not exist.
* You intended to execute a .NET SDK command:
No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
1: `/usr/bin/dotnet` failed: exit status: 145

Location:
src/steps/generic.rs:476

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.DEBUG Desktop notification: .NET failed
DEBUG Executing command `/usr/bin/notify-send -a Topgrade Topgrade '.NET failed'`

Retry? (y)es/(N)o/(s)hell/(q)uit
DEBUG Step "choosenim"
DEBUG Step "cargo"
DEBUG Path "/home/locutus/.cargo" exists
DEBUG Detected "/home/locutus/.cargo/bin/cargo" as "cargo"
DEBUG Step "Flutter"
DEBUG Step "go-global-update"
DEBUG Step "gup"
DEBUG Step "opam"
DEBUG Step "vcpkg"
DEBUG Step "pipx"
DEBUG Step "conda"
DEBUG Step "pip3"
DEBUG Detected "/usr/bin/python3" as "python3"
DEBUG Executing command `/usr/bin/python3 -m pip`

―― 07:35:03 - pip3 ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
DEBUG Executing command `/usr/bin/python3 -m pip install --upgrade --user pip`
Requirement already satisfied: pip in ./.local/lib/python3.10/site-packages (22.3.1)
DEBUG Step "ghcup"
DEBUG Step "stack"
DEBUG Step "tlmgr"
DEBUG Step "myrepos"
DEBUG Step "chezmoi"
DEBUG Step "jetpack"
DEBUG Step "vim"
DEBUG Detected "/usr/bin/vim" as "vim"
DEBUG Executing command `/usr/bin/vim --version`
DEBUG Step "Neovim"
DEBUG Step "The Ultimate vimrc"
DEBUG Step "voom"
DEBUG Step "Kakoune"
DEBUG Step "npm"
DEBUG Step "yarn"
DEBUG Step "pnpm"
DEBUG Step "Containers"
DEBUG Step "deno"
DEBUG Step "composer"
DEBUG Step "krew"
DEBUG Step "gem"
DEBUG Detected "/usr/bin/gem" as "gem"
DEBUG Step "rubygems"
DEBUG Detected "/usr/bin/gem" as "gem"
DEBUG Step "julia"
DEBUG Step "haxelib"
DEBUG Step "sheldon"
DEBUG Step "rtcl"
DEBUG Step "bin"
DEBUG Step "gcloud"
DEBUG Step "micro"
DEBUG Detected "/usr/bin/micro" as "micro"

―― 07:35:04 - micro ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
DEBUG Executing command `/usr/bin/micro -plugin update`
Checking for plugin updates
Nothing to install / update
DEBUG Step "raco"
DEBUG Step "spicetify"
DEBUG Step "GitHub CLI Extensions"
DEBUG Step "deb-get"
DEBUG Step "toolbx"
DEBUG Step "Flatpak"
DEBUG Detected "/usr/bin/flatpak" as "flatpak"

―― 07:35:04 - Flatpak User Packages ――――――――――――――――――――――――――――――――――――――――――――
DEBUG Executing command `/usr/bin/flatpak update --user`
Looking for updates…

Nothing to do.

―― 07:35:04 - Flatpak System Packages ――――――――――――――――――――――――――――――――――――――――――
DEBUG Executing command `/usr/bin/flatpak update --system`
Looking for updates…

Nothing to do.
DEBUG Step "snap"
DEBUG Step "pacstall"
DEBUG Step "pacdef"
DEBUG Step "protonup"
DEBUG Step "pihole"
DEBUG Step "Firmware upgrades"
DEBUG Detected "/usr/bin/fwupdmgr" as "fwupdmgr"
DEBUG Executing command `uname -r`
DEBUG Uname output: 6.0.12-zen1-1-zen


―― 07:35:05 - Firmware upgrades ――――――――――――――――――――――――――――――――――――――――――――――――
DEBUG Executing command `/usr/bin/fwupdmgr refresh`
Firmware metadata last refresh: 42 minutes ago. Use --force to refresh again.
DEBUG Executing command `/usr/bin/fwupdmgr get-updates`
Devices with no available firmware updates:
• ST8000AS0002-1NA17Z
• System Firmware
• Unifying Receiver
• Unifying Receiver
• WD Blue SN570 500GB
• WDC WDS500G2B0B-00YS70
Devices with the latest available firmware version:
• UEFI dbx
No updates available
DEBUG Step "Restarts"
DEBUG Step "Vagrant boxes"

―― 07:35:05 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
System update: OK
config-update: OK
Brew: SKIPPED: Cannot find "brew" in PATH
yadm: SKIPPED: Cannot find "yadm" in PATH
nix: SKIPPED: Cannot find "nix" in PATH
guix: SKIPPED: Cannot find "guix" in PATH
home-manager: SKIPPED: Cannot find "home-manager" in PATH
asdf: SKIPPED: Cannot find "asdf" in PATH
pkgin: SKIPPED: Cannot find "pkgin" in PATH
bun: SKIPPED: Cannot find "bun" in PATH
Git repositories: SKIPPED: No repositories to pull
zr: SKIPPED: Cannot find "zr" in PATH
antibody: SKIPPED: Cannot find "antibody" in PATH
antigen: SKIPPED: Path "/home/locutus/antigen.zsh" doesn't exist
zgenom: SKIPPED: Path "/home/locutus/.zgenom" doesn't exist
zplug: SKIPPED: Path "/home/locutus/.zplug" doesn't exist
zinit: SKIPPED: Path "/home/locutus/.zinit" doesn't exist
zi: SKIPPED: Path "/home/locutus/.zi" doesn't exist
zim: SKIPPED: Path "/home/locutus/.zim" doesn't exist
oh-my-zsh: OK
fisher: SKIPPED: `fisher` is not defined in `fish`
bash-it: SKIPPED: Path "/home/locutus/.bash_it" doesn't exist
oh-my-fish: SKIPPED: Path "/home/locutus/.local/share/omf/pkg/omf/functions/omf.fish" doesn't exist
fish-plug: SKIPPED: Path "/home/locutus/.local/share/fish/plug/kidonng/fish-plug/functions/plug.fish" doesn't exist
fundle: SKIPPED: Path "/home/locutus/.config/fish/fundle" doesn't exist
tmux: SKIPPED: Path "/home/locutus/.tmux/plugins/tpm/bin/update_plugins" doesn't exist
TLDR: OK
pearl: SKIPPED: Cannot find "pearl" in PATH
Gnome Shell Extensions: SKIPPED: Desktop doest not appear to be gnome
SDKMAN!: SKIPPED: Path "/home/locutus/.sdkman/bin/sdkman-init.sh" doesn't exist
rcm: SKIPPED: Cannot find "rcup" in PATH
apm: SKIPPED: Cannot find "apm" in PATH
fossil: SKIPPED: Cannot find "fossil" in PATH
rustup: OK
juliaup: SKIPPED: Cannot find "juliaup" in PATH
.NET: FAILED
choosenim: SKIPPED: Cannot find "choosenim" in PATH
cargo: SKIPPED: Path "/home/locutus/.cargo/.crates.toml" doesn't exist
Flutter: SKIPPED: Cannot find "flutter" in PATH
go-global-update: SKIPPED: Cannot find "go" in PATH
gup: SKIPPED: Cannot find "go" in PATH
opam: SKIPPED: Cannot find "opam" in PATH
vcpkg: SKIPPED: Cannot find "vcpkg" in PATH
pipx: SKIPPED: Cannot find "pipx" in PATH
conda: SKIPPED: Cannot find "conda" in PATH
pip3: OK
ghcup: SKIPPED: Cannot find "ghcup" in PATH
stack: SKIPPED: Cannot find "stack" in PATH
tlmgr: SKIPPED: tlmgr must be explicity enabled in the configuration to run in Android/Linux
myrepos: SKIPPED: Cannot find "mr" in PATH
chezmoi: SKIPPED: Cannot find "chezmoi" in PATH
jetpack: SKIPPED: Cannot find "jetpack" in PATH
vim: SKIPPED: Path "/home/locutus/.vim/vimrc" doesn't exist
Neovim: SKIPPED: Cannot find "nvim" in PATH
The Ultimate vimrc: SKIPPED: Path "/home/locutus/.vim_runtime" doesn't exist
voom: SKIPPED: Cannot find "voom" in PATH
Kakoune: SKIPPED: Cannot find "kak" in PATH
npm: SKIPPED: Cannot find "npm" in PATH
yarn: SKIPPED: Cannot find "yarn" in PATH
pnpm: SKIPPED: Cannot find "pnpm" in PATH
Containers: SKIPPED: Cannot find "docker" in PATH
deno: SKIPPED: Cannot find "deno" in PATH
composer: SKIPPED: Cannot find "composer" in PATH
krew: SKIPPED: Cannot find "kubectl-krew" in PATH
gem: SKIPPED: Path "/home/locutus/.gem" doesn't exist
rubygems: SKIPPED: Path "/home/locutus/.gem" doesn't exist
julia: SKIPPED: Cannot find "julia" in PATH
haxelib: SKIPPED: Cannot find "haxelib" in PATH
sheldon: SKIPPED: Cannot find "sheldon" in PATH
rtcl: SKIPPED: Cannot find "rupdate" in PATH
bin: SKIPPED: Cannot find "bin" in PATH
gcloud: SKIPPED: Cannot find "gcloud" in PATH
micro: OK
raco: SKIPPED: Cannot find "raco" in PATH
spicetify: SKIPPED: Cannot find "spicetify" in PATH
GitHub CLI Extensions: SKIPPED: Cannot find "gh" in PATH
deb-get: SKIPPED: Cannot find "deb-get" in PATH
toolbx: SKIPPED: Cannot find "toolbox" in PATH
Flatpak: OK
snap: SKIPPED: Cannot find "snap" in PATH
pacstall: SKIPPED: Cannot find "pacstall" in PATH
pacdef: SKIPPED: Cannot find "pacdef" in PATH
protonup: SKIPPED: Cannot find "protonup" in PATH
pihole: SKIPPED: Cannot find "pihole" in PATH
Firmware upgrades: OK
Restarts: SKIPPED: Cannot find "needrestart" in PATH
Vagrant boxes: SKIPPED: Cannot find "vagrant" in PATH
DEBUG Desktop notification: Topgrade finished with errors
DEBUG Executing command `/usr/bin/notify-send -a Topgrade Topgrade 'Topgrade finished with errors'`
~~~

### PR DESCRIPTION
**Pull request by DottoDev**
Closes #225
Closes #269 
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The code compiles (`cargo build`)
- [x] The code passes rustfmt (`cargo fmt`)
- [x] The code passes clippy (`cargo clippy`)
- [x] The code passes tests (`cargo test`)
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.
@BackSpace54 could you please try this out

### CODE REVIEW

File: src/steps/generic.rs [hunk 1]
```diff
@@ -479,31 +479,33 @@ pub fn run_composer_update(ctx: &ExecutionContext) -> Result<()> {
...
 
-    let output = Command::new(dotnet)
-        .args(["tool", "list", "--global"])
-        .output_checked_utf8()?;
-
-    if !output.stdout.starts_with("Package Id") {
-        return Err(SkipStep(String::from("dotnet did not output packages")).into());
-    }
+    let dotnet_tool_output = ctx.run_type().execute(&dotnet).arg("tool").output().err().unwrap();
+    if dotnet_tool_output.to_string().contains("Usage") {
```
Comment (pan93412) [inline src/steps/generic.rs:483]: `dotnet` will display the localized text if I didn't remember wrong. When the localized text is shown, this condition may be failed.

**Review by pan93412 — CHANGES_REQUESTED** [review]

File: src/steps/generic.rs (hunk 1 above)
Comment (DottoDev) [reply src/steps/generic.rs:483]: I think I know how to solve that.

Comment (DottoDev) [reply src/steps/generic.rs]: Should work now because it now queries one line which is identical in every language

**Comment by DottoDev** [comment]
True, haven't looked at that because that was still from the old version.

**Comment by pan93412** [comment]
Does `dotnet` provide a JSON-like output mode for machines to read?

**Comment by DottoDev** [comment]
Looked at the manual and it seems like it doesn't.

**Comment by DottoDev** [comment]
@BackSpace54 comming back to this issue, shouldn't tool only be listed in the output of `dotnet -h` if it's listed

**Comment by BackSpace54** [comment]
> @BackSpace54 comming back to this issue, shouldn't tool only be listed in the output of `dotnet -h` when it's available

Well, tested `dotnet -h` on Linux and Windows and yes _tool_ option is only listed with dotnet SDK and whatever language is set.

**Comment by DottoDev** [comment]
> > @BackSpace54 comming back to this issue, shouldn't tool only be listed in the output of `dotnet -h` when it's available
> 
> Well, tested `dotnet -h` on Linux and Windows and yes _tool_ option is only listed with dotnet SDK and whatever language is set.

This should work now

**Comment by Jisu-Woniu** [comment]
Still don't work on my Ubuntu.

(System language is zh-CN, Simplified Chinese)

图片

**Comment by DottoDev** [comment]
An idea would be to check if it contains a string with *.*.* instead of Package ID

**Comment by cxt666** [comment]
Fixed for me; Version "Topgrade 10.3.1"

**Comment by Jisu-Woniu** [comment]
An idea: add an environment variable `LANG=C` when executing `dotnet tool list -g` command on Linux.

Not sure whether this would work on Windows.

**Comment by Jisu-Woniu** [comment]
> Hi, maybe this could do the trick at least on Linux/MacOS, before line #478 of generic.rs when you test `!output.stdout.starts_with("Package Id")` if you pass this bash command `export DOTNET_CLI_UI_LANGUAGE=en && dotnet tool list -g && unset DOTNET_CLI_UI_LANGUAGE` you'll get output in english (then back to default value with the unset command) so you get the "Package ID" value to test if package(s) are installed or not.
> 
> On Windows the shell command `set DOTNET_CLI_UI_LANGUAGE=en && start /I dotnet tool list -g && set DOTNET_CLI_UI_LANGUAGE=` send the output in english (then unset language) but in a new terminal, not sure you can get the output... Put output in a file with this command `set DOTNET_CLI_UI_LANGUAGE=en && start /I cmd /C "dotnet tool list -g > %TEMP%\dotnet.txt" && set DOTNET_CLI_UI_LANGUAGE=`

This command seems to work on my machine.
