### PR TITLE
Warn if a step was skipped due to a missing sudo

### LINKED ISSUE #370: Support for apk
### Which tool is this about? Where is its repository?
https://github.com/alpinelinux/apk-tools
### Which operating systems are supported by this tool?
Linux Alpine and Chimera as far as i know, but can be installed in other distros
### What should Topgrade do to figure out if the tool needs to be invoked?
apx command exists 
apk --version
### Which exact commands should Topgrade run?
apk update
apk upgrade --available
apk fix

thanks

### LINKED ISSUE #530: Topgrade silently skips `apt` update if `sudo` is not installed
## Erroneous Behavior
`topgrade` silently skips the `apt-get` system update step on Debian Bookworm if `sudo` is not installed; even if `topgrade` is run as `root`.

## Expected Behavior
If the current user is `root`, `topgrade` should run `apt-get` (or other commands) without `sudo` to perform the update. Alternatively, `topgrade` should raise a warning or error instead of silently skipping this step.

## Steps to reproduce
- Install a minimal Debian Bookworm without `sudo` (i.e. from the netinstall image)
- Install `rust` via rustup
- Install `topgrade` via `cargo`

## Problem persists without calling from topgrade
- [x] Yes
- [x] No

`Yes` if I copy the **exact** command with `sudo` (since `sudo` is not installed), `No` if I just execute `apt-get update`.

## Did you run topgrade through `Remote Execution`
- [x] Yes
- [x] No

If yes, does the issue still occur when you run topgrade directlly in your
remote host

- [x] Yes
- [ ] No

## Additional Details
- Operation System/Version: Debian Bookworm

- Installation: `topgrade` via `cargo` via `rustup`

- Topgrade version (`topgrade -V`): `Topgrade 12.0.2`

## Verbose Output (`topgrade -v`)

<details>
<pre>
DEBUG Configuration at /root/.config/topgrade.toml
DEBUG Loaded configuration: ConfigFile { include: None, misc: Some(Misc { pre_sudo: None, sudo_command: None, git_repos: None, predefined_git_repos: None, disable: None, ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, git_arguments: None, tmux_arguments: None, set_title: None, display_time: None, assume_yes: None, yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, no_retry: None, run_in_tmux: None, cleanup: None, notify_each_step: None, accept_all_windows_updates: None, skip_notify: None, bashit_branch: None, only: None, no_self_update: None }), pre_commands: None, post_commands: None, commands: Some({"restic": "restic self-update"}), python: None, composer: None, brew: None, linux: None, git: None, windows: None, npm: None, yarn: None, vim: None, firmware: None, vagrant: None, flatpak: None, distrobox: None }
DEBUG Version: 12.0.2
DEBUG OS: x86_64-unknown-linux-gnu
DEBUG Args { inner: ["topgrade", "-v", "--only=system"] }
DEBUG Binary path: Ok("/root/.cargo/bin/topgrade")
DEBUG Self Update: false
DEBUG Detected "/usr/bin/git" as "git"
DEBUG Cannot find "pwsh"
DEBUG Cannot find "powershell"
DEBUG Path "/root/.config/emacs" doesn't exist
DEBUG Path "/root/.emacs.d" doesn't exist
DEBUG Cannot find "doas"
DEBUG Cannot find "please"
DEBUG Cannot find "sudo"
DEBUG Cannot find "gsudo"
DEBUG Cannot find "pkexec"
DEBUG Step "System update"

── 02:07:40 - System update ────────────────────────────────────────────────────
DEBUG Cannot find "apt-fast"
DEBUG Cannot find "mist"
DEBUG Step "pihole"
DEBUG /root/.ideavimrc does not exists
DEBUG /root/.intellimacs does not exists
DEBUG /root/.zshrc does not exists
DEBUG /root/.config/fish does not exists
DEBUG /root/.config/openbox does not exists
DEBUG /root/.config/bspwm does not exists
DEBUG /root/.config/i3 does not exists
DEBUG /root/.config/sway does not exists

── 02:07:40 - Summary ──────────────────────────────────────────────────────────
System update: SKIPPED: Require sudo or counterpart but not found, skip
pihole: SKIPPED: Require sudo or counterpart but not found, skip
DEBUG Desktop notification: Topgrade finished successfully
</pre>
</details>

### PR DESCRIPTION
**Pull request by AThePeanut4**
## What does this PR do

Following on from #1341, `require_sudo()` now returns a new `MissingSudo` error rather than just `SkipStep`. If a step errors with this, a warning message is printed, a yellow "SKIPPED" entry is shown in the summary, and a message informing the user to install sudo or an equivalent is printed at the end.

This change means that `require_sudo()` should now only be run after the separator is printed, since it now throws a "noisy" error rather than silently skipping the step.

## Standards checklist

- [x] The PR title is descriptive
- [x] I have read `CONTRIBUTING.md`
- [x] *Optional:* I have tested the code myself
- [x] If this PR introduces new user-facing messages they are translated

Fixes #370
Fixes #530

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -224,12 +225,30 @@ fn run() -> Result<()> {
...
         }
+
+        if skipped_missing_sudo {
+            print_warning(t!(
+                "\nSome steps were skipped as sudo or equivalent could not be found."
+            ));
+
+            #[cfg(unix)]
+            print_warning(t!(
+                "Install one of sudo, doas, pkexec, run0 or please to run these steps."
```
Comment (GideonBear) [inline src/main.rs]: Since `please` is also a normal English word, I can imagine this being both trippy to read, and having bad translations.
```suggestion
                "Install one of `sudo`, `doas`, `pkexec`, `run0` or `please` to run these steps."
```

**Comment by GideonBear** [comment]
Could you send a screenshot of these warnings in action?

**Comment by atoerien** [comment]
> Could you send a screenshot of these warnings in action?

Yeah it's a bit tricky to force the warning to show up :laughing:

The easiest I found on Linux was to unset PATH and run the system step, since it only does `require("pacman")` in my case *after* printing the separator and requiring sudo.

image

Edit: actually that only works on Arch because it never actually does `require("pacman")`, it just uses `"pacman"`...

**Comment by GideonBear** [comment]
Looks great, thanks!
