### PR TITLE
fix(bun): skip self-update if not installed via official script

### LINKED ISSUE #892: Add bun sudo option? bun doesnt upgrade without it if installed on /usr/bin(from aur)
## Erroneous Behavior

bun upgrade not working
## Expected Behavior

bun upgraded
## Steps to reproduce

install `bun-bin` from the aur then use topgrade 2 update
## Possible Cause (Optional)

no sudo access
## Problem persists without calling from topgrade

- [-] Yes
- [ ] No

## Did you run topgrade through `Remote Execution`

- [ ] Yes
- [-] No

If yes, does the issue still occur when you run topgrade directlly in your
remote host

- [ ] Yes
- [ ] No

## Configuration file (Optional)

```toml
YES WE NEED 2 ADD A use_sudo like npm
```

## Additional Details
- Operation System/Version
  
Arch Rolling release
- Installation
  
AUR
- Topgrade version (`topgrade -V`)
Topgrade 14.0.1
## Verbose Output (`topgrade -v`)

doesnt matter
<details>
<pre>

</pre>
</details>

### PR DESCRIPTION
**Pull request by atoerien**
## What does this PR do

Rebase of #894 on `main`.

After this PR, we only update bun if it is installed through the official script. We determine this by checking if the binary location is a descendant of `bun_install_env`, which will be set through the environment variable `$BUN_INSTALL`, and defaults to `$HOME/.bun`.

Closes #892
Closes #894 

## Standards checklist

- [x] The PR title is descriptive
- [x] I have read `CONTRIBUTING.md`
- [x] *Optional:* I have tested the code myself
- [ ] If this PR introduces new user-facing messages they are translated

### CODE REVIEW

File: src/steps/generic.rs [hunk 1]
```diff
@@ -1569,9 +1569,25 @@ pub fn run_zvm(ctx: &ExecutionContext) -> Result<()> {
...
 
-    print_separator("Bun");
-
-    ctx.execute(bun).arg("upgrade").status_checked()
+    // From the official install script (both install.sh and install.ps1), Bun uses
+    // the path set in this variable as the install root, and its defaults to
+    // `$HOME/.bun`
+    //
+    // UNIX: https://bun.sh/install.sh
+    // Windows:https://bun.sh/install.ps1
```
Comment (GideonBear) [inline src/steps/generic.rs]:
```suggestion
    // Windows: https://bun.sh/install.ps1
```
