### PR TITLE
Fix "WSL already reported" panic

### LINKED ISSUE #1246: Panic "WSL already reported" due to duplicate step reporting
## Description
Topgrade panics with "WSL already reported" when both the WSL step (running topgrade inside WSL distributions) and the WSL Update step (updating WSL itself) attempt to report using the same identifier.

## Error Message
```
The application panicked (crashed).
Message:  WSL already reported
Location: src\report.rs:37
```

## Root Cause
The debug logs show two separate WSL-related steps:
1. **WSL step**: Runs `topgrade` inside each WSL distribution 
2. **WSL Update step**: Updates WSL itself using `wsl --update`

Both steps appear to be using the same reporting key/identifier, causing a collision in the reporting system when the second step tries to report its results.

## Environment
- **OS**: Windows with WSL (Debian)
- **Topgrade version**: Built from main branch
- **Command**: `.\target\debug\topgrade.exe --verbose`

## Steps to Reproduce
1. Run Topgrade on Windows with WSL installed
2. Let both WSL steps execute (WSL distribution updates + WSL system update)
3. Observe panic after WSL update completes

## Debug Evidence
From the verbose output:
```
DEBUG Step "WSL"  # First WSL step (runs topgrade in distributions)
...
DEBUG Step "WSL"  # Second WSL step appears
── 02:28:15 - Update WSL ───  # WSL Update step runs
Checking for updates.
The most recent version of Windows Subsystem for Linux is already installed.
The application panicked (crashed).
Message:  WSL already reported
```

## Expected Behavior
Both WSL-related steps should be able to report their results independently without conflicts.

## Actual Behavior
The second WSL-related step (WSL Update) cannot report because the first WSL step has already used the same reporting identifier.

## Suggested Fix
The two WSL steps need distinct reporting identifiers:
- WSL distributions step: "WSL" or "WSL Distributions"  
- WSL system update step: "WSL Update" or "WSL System"

## Code Location
- Panic occurs in `src\report.rs:37`
- WSL steps likely defined in `src\steps\os\windows.rs`

## Workaround
```toml
[misc]
disable = ["wsl", "wsl_update"]
```

## Additional Context
- This is a **regression** - the issue existed before, was fixed, but has reappeared
- The WSL functionality itself works correctly - only the reporting system has the bug
- Both steps complete their actual work successfully before the panic occurs

### PR DESCRIPTION
**Pull request by AThePeanut4**
## What does this PR do

Fix an assertion failure caused by two steps using "WSL" as the key, when using a debug build.

The assertion is here:
https://github.com/topgrade-rs/topgrade/blob/3961ef61c809b7476e818ac36f7a4a0a4691b1b5/src/report.rs#L37

While investigating I noticed that `Report` was basically just a thin wrapper around a `Vec`, which seemed unnecessary to me. So this also removes that entirely, storing the `Vec` directly in the `Runner` and moving `push_result()` to `Runner` (and removes the function's unnecessary use of `Option` and `Into<...>` as well).

## Standards checklist

- [x] The PR title is descriptive
- [x] I have read `CONTRIBUTING.md`
- [x] *Optional:* I have tested the code myself
- [x] If this PR introduces new user-facing messages they are translated

Fixes #1246

### CODE REVIEW

**Comment by GideonBear** [comment]
@niStee do #1246 or #1136 happen on this branch? Or does this fix both?

File: src/main.rs [hunk 1]
```diff
@@ -6,7 +6,6 @@ use std::path::PathBuf;
 use std::process::exit;
 use std::time::Duration;
 
-use crate::breaking_changes::{first_run_of_major_release, print_breaking_changes, should_skip, write_keep_file};
```
Comment (GideonBear) [inline src/main.rs:9]: Please move this back

File: src/step.rs [hunk 2]
```diff
@@ -664,7 +664,7 @@ impl Step {
             WslUpdate =>
             {
                 #[cfg(windows)]
-                runner.execute(*self, "WSL", || windows::update_wsl(ctx))?
+                runner.execute(*self, "WSL Update", || windows::update_wsl(ctx))?
```
Comment (GideonBear) [inline src/step.rs]: Should match separator
```suggestion
                runner.execute(*self, "Update WSL", || windows::update_wsl(ctx))?
```

**Review by GideonBear — CHANGES_REQUESTED** [review]

**Comment by niStee** [comment]
> @niStee do #1246 or #1136 happen on this branch? Or does this fix both?

I'll check this later.
I'm not at home at the moment.

**Comment by atoerien** [comment]
I was able to reproduce #1246 (just run a debug build of Topgrade on Windows, with WSL installed), so it does fix that for me. #1136 looks completely unrelated, so I don't think this should fix it, but I haven't looked into it.

File: src/main.rs (hunk 1 above)
Comment (atoerien) [reply src/main.rs:9]: :(

File: src/step.rs (hunk 2 above)
Comment (atoerien) [reply src/step.rs]: Ah I forgot about the separator text. Will fix.

**Comment by niStee** [comment]
> I was able to reproduce #1246 (just run a debug build of Topgrade on Windows, with WSL installed), so it does fix that for me. #1136 looks completely unrelated, so I don't think this should fix it, but I haven't looked into it.

I believe https://github.com/topgrade-rs/topgrade/issues/1136 must be fixed in https://github.com/topgrade-rs/topgrade/blob/fec08a5ad125a309fbb504c16dc06d89304ab9de/src/steps/os/windows.rs#L125-L132
like https://github.com/niStee/topgrade/blob/a7b315a2c04143c442b5413d1cb94c0f4cc41ef9/src/steps/os/windows/mod.rs#L131-L138

**Comment by GideonBear** [comment]
Thanks! :heart:

**Comment by atoerien** [comment]
> I believe #1136 must be fixed in
> 
> https://github.com/topgrade-rs/topgrade/blob/fec08a5ad125a309fbb504c16dc06d89304ab9de/src/steps/os/windows.rs#L125-L132
> 
> like https://github.com/niStee/topgrade/blob/a7b315a2c04143c442b5413d1cb94c0f4cc41ef9/src/steps/os/windows/mod.rs#L131-L138

@niStee I haven't been able to reproduce the bug, but if the change you link there fixes it then I think go ahead and make a PR for it. The only potential issue I can see is if you *intentionally* had a WSL distribution with an empty name, or if you had one with leading/trailing spaces in the name (`" foo"`) to cause issues with the `trim()`.
