### PR TITLE
Fixes paru/yay -Pw return code error

### LINKED ISSUE #220: Repo packages error Paru/Yay
## What did you expect to happen?

For it to work lol...

## What actually happened?

It error-ed out on system update with Paru n Yay. Works fine without them

## Additional Details
- Which operating system or Linux distribution are you using? +> ArchLinux (XeroLinux)
- How did you install Topgrade? => AUR
- Which version are you running? => 10.2.0

<details>
<pre>
-> error installing repo packages
System update failed: 
   0: Command failed: `/usr/bin/yay --pacman pacman -Syu`
   1: `/usr/bin/yay` failed: exit status: 1

Location:
   src/steps/os/archlinux.rs:49

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

System update failed: 
   0: Command failed: `/usr/bin/paru -Pw`
   1: `/usr/bin/paru` failed: exit status: 1

Location:
   src/steps/os/archlinux.rs:34

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
</pre>
</details>

### PR DESCRIPTION
**Pull request by DottoDev**
Closes #220 
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The code compiles (`cargo build`)
- [x] The code passes rustfmt (`cargo fmt`)
- [x] The code passes clippy (`cargo clippy`)
- [x] The code passes tests (`cargo test`)
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.
@TechXero

### CODE REVIEW

**Comment by ahuston-0** [comment]
Cross-posting from #220 but this is no longer throwing an error with either paru or yay on my system.

**Comment by float3** [comment]
I was experiencing the `paru -Pw`issue, this pr fixed it for me

**Comment by TechXero** [comment]
Waiting for AUR package to be updated..

File: src/steps/os/archlinux.rs [hunk 1]
```diff
@@ -32,7 +31,10 @@ pub struct YayParu {
 impl ArchPackageManager for YayParu {
     fn upgrade(&self, ctx: &ExecutionContext) -> Result<()> {
         if ctx.config().show_arch_news() {
-            Command::new(&self.executable).arg("-Pw").status_checked()?;
+            ctx.run_type()
+                .execute(&self.executable)
+                .arg("-Pw")
+                .status_checked_with_codes(&[1, 0])?;
```
Comment (pan93412) [inline src/steps/os/archlinux.rs:37]: May it show “success” when this command failed with return code 1?

**Comment by Samisafool** [comment]
Please merge this, topgrade fails without it on my system

File: src/steps/os/archlinux.rs (hunk 1 above)
Comment (DottoDev) [reply src/steps/os/archlinux.rs:37]: How do you mean that?

Comment (9999years) [reply src/steps/os/archlinux.rs:37]: This will consider the command (`paru -Pw` or `yay -Pw`) to have succeeded if it exits with return codes 1 or 0. It won't print "success" but it will continue to execute `topgrade`. (It won't fail.)

Comment (DottoDev) [reply src/steps/os/archlinux.rs:37]: I don't see a reason why we should print a success because it still errors out if something goes wrong.

**Comment by DottoDev** [comment]
@pan93412 @9999years could one of you sign this PR off?

**Comment by pan93412** [comment]
> @pan93412 @9999years could one of you sign this PR off?

I don't think that this is necessary. I will approve it though.

**Review by pan93412 — APPROVED** [review]
