### PR TITLE
Fix conflict between hx (hexdump alternative) and Helix

### LINKED ISSUE #848: Helix name clash with hexdump alternative
## Erroneous Behavior

Topgrade attempts to upgrade "Helix" upon finding a `hx` binary, which clashes with cargo's [`hx`](https://crates.io/crates/hx) binary (alt to hexdump).

## Expected Behavior

The existence of an `hx` binary shouldn't trigger a helix upgrade on its own.

## Steps to reproduce

Have `hx` installed, but not the Helix text editor.

```
cargo install hx
```

```
topgrade --only helix
# incorrect detection of helix; also happens with `topgrade` alone.
```

## Possible Cause (Optional)

This seems to be the problematic [line](https://github.com/topgrade-rs/topgrade/blob/main/src/steps/generic.rs#L827).

## Additional Details
- Operation System/Version
  

- Installation
  

- Topgrade version (`topgrade -V`)

## Verbose Output (`topgrade -v`)

<details>
<pre>
topgrade --only helix

── 12:20:37 - Helix ────────────────────────────────────────────────────────────
error: unexpected argument '--grammar' found

  tip: to pass '--grammar' as a value, use '-- --grammar'

Usage: hx [OPTIONS] [INPUTFILE]

For more information, try '--help'.

── 12:20:37 - Summary ──────────────────────────────────────────────────────────
helix: FAILED
</pre>
</details>

### PR DESCRIPTION
**Pull request by GideonBear**
## What does this PR do
Like #1092, fix the conflict by inspecting the output of `hx --help`.
Closes #848

## Standards checklist

- [x] The PR title is descriptive
- [x] I have read `CONTRIBUTING.md`
- [x] *Optional:* I have tested the code myself
- [ ] If this PR introduces new user-facing messages they are translated

### CODE REVIEW

File: src/steps/generic.rs [hunk 1]
```diff
@@ -1006,8 +1006,39 @@ pub fn run_dotnet_upgrade(ctx: &ExecutionContext) -> Result<()> {
     Ok(())
 }
 
+enum Hx {
+    Helix(PathBuf),
+    HxHexdump,
```
Comment (SteveLauC) [inline src/steps/generic.rs:1011]: This approach looks good to me, but I don't want to pull a tool that Topgrade does not support in. Can we just check if this `hx` is Helix or not. For example, `hx --help` contains "helix" and "text editor", can we make use of them?

Comment (GideonBear) [reply src/steps/generic.rs:1011]: Fair point, changed it

**Review by SteveLauC — APPROVED** [review]
LG, thanks!
