### PR TITLE
fix(brew): fix brew casks and incomplete formula update on linux when using isolated user

### LINKED ISSUE #1599: Output of brew --version has changed.
## Checklist

- [ x] I have searched the issue tracker for relevant or duplicate issues.

## Erroneous Behavior

I cannot upgrade packages on homebrew via Topgrade.

## Expected Behavior

Homebrew packages should be updated.

## Steps to reproduce

Simply run topgrade.

## Possible Cause (Optional)

Here is the output, maybe my homebrew version got corrupted somehow?

```
── 21:30:06 - Brew (sudo as user 'linuxbrew') ──────────────────────────────────
==> Updating Homebrew...
Already up-to-date.
Brew Cask failed:
   0: The output of `brew --version` changed: Invalid version. This is not your fault, this is an issue in Topgrade. Please open an issue at: https://github.com/topgrade-rs/topgrade/issues/new?template=bug_report.md
   1: unexpected character '>' while parsing major version number
```

## Problem persists without calling from topgrade

- [ ] Yes
- [X ] No

Works without topgrade.

## Ran through `Remote Execution`

- [ ] Yes
- [X ] No

## Configuration file (Optional)

```toml
# Include any additional configuration file(s)
# [include] sections are processed in the order you write them
# Files in $CONFIG_DIR/topgrade.d/ are automatically included before this file
[include]
# paths = ["/etc/topgrade.toml"]


[misc]
# On Unix systems, Topgrade should not be run as root, it
# will run commands with sudo or equivalent where needed.
# Set this to true to suppress the warning and confirmation
# prompt if Topgrade detects it is being run as root.
# (default: false)
# allow_root = false

# Run `sudo -v` to cache credentials at the start of the run
# This avoids a blocking password prompt in the middle of an unattended run
# (default: false)
# pre_sudo = false

# Sudo command to be used
# sudo_command = "sudo"

# Disable specific steps - same options as the command line flag
# disable = ["system", "emacs"]
disable = ["vcpkg", "yarn", "node", "pip3", "waydroid", "powershell", "composer", "containers", "vscode", "vscodium"]

# Ignore failures for these steps
# ignore_failures = ["powershell"]

# List of remote machines with Topgrade installed on them
# remote_topgrades = ["toothless", "pi", "parnas"]

# Path to Topgrade executable on remote machines
# remote_topgrade_path = ".cargo/bin/topgrade"

# Arguments to pass to SSH when upgrading remote systems
# ssh_arguments = "-o ConnectTimeout=2"

# Arguments to pass tmux when pulling Repositories
# tmux_arguments = "-S /var/tmux.sock"

# Do not set the terminal title (default: true)
# set_title = true

# Display the time in step titles (default: true)
# display_time = true

# Don't ask for confirmations (no default value)
# assume_yes = true

# Do not ask to retry failed steps (default: false)
# no_retry = true

# Show the reason for skipped steps (default: false)
# This has no effect if the "only" option is specified
# show_skipped = true

# Run inside tmux (default: false)
# run_in_tmux = true

# Changes the way topgrade interacts with
# the tmux session, creating the session
# and only attaching to it if not inside tmux
# (default: "attach_if_not_in_session", allowed values: "attach_if_not_in_session", "attach_always")
# tmux_session_mode = "attach_if_not_in_session"

# Cleanup temporary or old files (default: false)
# cleanup = true

# Send a notification for every step (default: false)
# notify_each_step = false

# Skip sending a notification at the end of a run (default: false)
# skip_notify = true

# The Bash-it branch to update (default: "stable")
# bashit_branch = "stable"

# Run specific steps - same options as the command line flag
# only = ["system", "emacs"]

# Whether to self update
#
# this will be ignored if the binary is built without self update support
#
# available also via setting the environment variable TOPGRADE_NO_SELF_UPGRADE)
# no_self_update = true

# Extra tracing filter directives
# These are prepended to the `--log-filter` argument
# See: https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html#directives
# log_filters = ["topgrade::command=debug", "warn"]

# Whether to show a distribution-specific summary if applicable, e.g. listing
# Pacman backup configuration files (*.pacsave and *.pacnew)
# (default: true)
# show_distribution_summary = false


# Commands to run before anything
[pre_commands]
# "Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"


# Commands to run after anything
[post_commands]
# "Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"


# Custom commands
[commands]
# "Python Environment" = "~/dev/.env/bin/pip install -i https://pypi.python.org/simple -U --upgrade-strategy eager jupyter"
# "Custom command using interactive shell (unix)" = "-i vim_upgrade"


[python]
# enable_pip_review = true                         ###disabled by default
# enable_pip_review_local = true                   ###disabled by default
# enable_pipupgrade = true                         ###disabled by default
# pipupgrade_arguments = "-y -u --pip-path pip"    ###disabled by default

# For the poetry step, by default, Topgrade skips its update if poetry is not
# installed with the official script. This configuration entry forces Topgrade
# to run the update in this case.
#
# (default: false)
# poetry_force_self_update = true


#[conda]
# Additional named conda environments to update (`conda env update -n env_name`)
# env_names = [
#     "Toolbox",
#     "PyTorch"
# ]
# Additional conda environment paths to update (`conda env update -p env_path`)
# env_paths = [
#     "~/webserver/.conda/",
#     "~/experiments/.conda/"
# ]


[composer]
# self_update = true


[brew]
# For the BrewCask step
# If `Repo Cask Upgrade` exists, then use the `-a` option.
# Otherwise, use the `--greedy` option.
# greedy_cask = true

# For the BrewCask step
# If `Repo Cask Upgrade` does not exist, then use the `--greedy_latest` option.
# NOTE: the above entry `greedy_cask` contains this entry, though you can enable
# both of them, they won't clash with each other.
# greedy_latest = true

# For the BrewCask step
# If `Repo Cask Upgrade` does not exist, then use the `--greedy_auto_updates` option.
# NOTE: the above entry `greedy_cask` contains this entry, though you can enable
# both of them, they won't clash with each other.
# greedy_auto_updates = true

# For the BrewFormula step
# Execute `brew autoremove` after the step.
# autoremove = true

# For the BrewFormula step
# Upgrade formulae built from the HEAD branch; `brew upgrade --fetch-HEAD`
# fetch_head = true


[linux]
# Arch Package Manager to use.
# Allowed values:
#   autodetect, aura, garuda_update, pacman, pamac, paru, pikaur, trizen, yay
# arch_package_manager = "pacman"

# Arguments to pass yay (or paru) when updating packages
# yay_arguments = "--nodevel"

# Arguments to pass dnf when updating packages
# dnf_arguments = "--refresh"

# aura_aur_arguments = "-kx"

# aura_pacman_arguments = ""
# garuda_update_arguments = ""

# show_arch_news = true

# trizen_arguments = "--devel"

# pikaur_arguments = ""

# pamac_arguments = "--no-devel"

# enable_tlmgr = true

# emerge_sync_flags = "-q"

# emerge_update_flags = "-uDNa --with-bdeps=y world"

# redhat_distro_sync = false

# suse_dup = false

# rpm_ostree = false

# For Fedora/CentOS/RHEL Atomic variants, if `bootc` is available and this configuration entry is set to true, use
# it to do the update - Will also supersede rpm-ostree if enabled
# (default: false)
# bootc = false

# nix_arguments = "--flake"

# nix_env_arguments = "--prebuilt-only"

# Extra Home Manager arguments
# home_manager_arguments = ["--flake", "file"]


#[mandb]
# Enable the mandb step (to update manual entries).
# Mandb is updated in the background by a service on most systems by default.
# (default: false)
# enable = true


[git]
# How many repos to pull at max in parallel
# max_concurrency = 5

# Additional git repositories to pull
# repos = [
#     "~/src/*/",
#     "~/.config/something"
# ]

# Don't pull the predefined git repos
# pull_predefined = false

# Arguments to pass Git when pulling Repositories
# arguments = "--rebase --autostash"


[windows]
# Manually select Windows updates
# accept_all_updates = false

# Controls whether to automatically reboot the computer when updates are
# installed that request it. (default: "no", allowed values: "yes", "no", "ask")
# updates_auto_reboot = "yes"

# open_remotes_in_new_terminal = true

# wsl_update_pre_release = true

# wsl_update_use_web_download = true

# The default for winget_install_silently is true,
# this example turns off silent install.
# winget_install_silently = false

# Causes Topgrade to rename itself during the run to allow package managers
# to upgrade it. Use this only if you installed Topgrade by using a package
# manager such as Scoop or Cargo
# self_rename = true

# Use sudo to elevate privileges for the Windows Package Manager (winget)
# Only use this option if you want to run the Winget step in sudo-mode.
# Running winget in sudo-mode is generally not recommended, as not every
# package supports installing / upgrading in sudo-mode and it may cause issues
# with some packages or may even cause the Winget-step to fail.
# If any problems occur, please try running Topgrade without this option first
# before reporting an issue.
# (default: false)
# winget_use_sudo = true


[npm]
# Use sudo if the NPM directory isn't owned by the current user
# use_sudo = true


[yarn]
# Run `yarn global upgrade` with `sudo`
# use_sudo = true


[deno]
# Upgrade deno executable to the given version.
# version = "stable"


[vim]
# For `vim-plug`, execute `PlugUpdate!` instead of `PlugUpdate`
# force_plug_update = true


[firmware]
# Offer to update firmware; if false just check for and display available updates
# upgrade = true


[vagrant]
# Vagrant directories
# directories = []

# power on vagrant boxes if needed
# power_on = true

# Always suspend vagrant boxes instead of powering off
# always_suspend = true


[flatpak]
# Use sudo for updating the system-wide installation
# use_sudo = true


[distrobox]
# use_root = false

# containers = ["archlinux-latest"]
[containers]
# Specify the containers to ignore while updating (Wildcard supported)
# ignored_containers = ["ghcr.io/rancher-sandbox/rancher-desktop/rdx-proxy:latest", "docker.io*"]
# Specify the runtime to use for containers (default: "docker", allowed values: "docker", "podman")
# runtime = "podman"

[lensfun]
# If disabled, Topgrade invokes `lensfun‑update‑data` without root privilege,
# then the update will be only available to you. Otherwise, `sudo` is required,
# and the update will be installed system-wide, i.e., available to all users.
# (default: false)
# use_sudo = false

[julia]
# If disabled, Topgrade invokes julia with the --startup-file=no CLI option.
#
# This may be desirable to avoid loading outdated packages with "using" directives
# in the startup file, which might cause the update run to fail.
# (default: true)
# startup_file = true

[zigup]
# Version strings passed to zigup.
# These may be pinned versions such as "0.13.0" or branches such as "master".
# Each one will be updated in its own zigup invocation.
# (default: ["master"])
# target_versions = ["master", "0.13.0"]

# Specifies the directory that the zig files will be installed to.
# If defined, passed with the --install-dir command line flag.
# If not defined, zigup will use its default behaviour.
# (default: not defined)
# install_dir = "~/.zig"

# Specifies the path of the symlink which will be set to point at the default compiler version.
# If defined, passed with the --path-link command line flag.
# If not defined, zigup will use its default behaviour.
# This is not meaningful if set_default is not enabled.
# (default: not defined)
# path_link = "~/.bin/zig"

# If enabled, run `zigup clean` after updating all versions.
# If enabled, each updated version above will be marked with `zigup keep`.
# (default: false)
# cleanup = false

[vscode]
# If this is set and is a non-empty string, it specifies the profile the
# extensions should be updated for.
# (default: this won't be set by default)
# profile = ""

#[pixi]
# Show the release notes of the latest pixi release
# during the pixi step
# (default: false)
# include_release_notes = false

#[doom]
# If this is set to true, the `--aot` flag is added to `doom upgrade`,
# which enables ahead-of-time native compilation of packages.
# (default: false)
# aot = true

#[rustup]
# If set, updates only these channels.
# (default: [] (all channels))
# channels = ["stable"]
```

## Additional Details

- Operation System/Version
Operating System: Fedora Linux 43
KDE Plasma Version: 6.5.3
KDE Frameworks Version: 6.20.0
Qt Version: 6.10.1
Kernel Version: 6.17.9-300.fc43.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5800X3D 8-Core Processor
Memory: 32 GiB of RAM (31.2 GiB usable)
Graphics Processor: AMD Radeon RX 7800 XT

- Installation
The copr repo found [here](https://copr.fedorainfracloud.org/coprs/lilay/topgrade/).

- Topgrade version (`topgrade -V`)
topgrade 16.6.1

## Verbose Output (`topgrade -v`)
Relevant linuxbrew stuff here.
<details>
<pre>
── 21:33:46 - Brew (sudo as user 'linuxbrew') ──────────────────────────────────
DEBUG Executing command `/usr/bin/sudo -H -u linuxbrew /home/claire/.linuxbrew/bin/brew update`
==> Updating Homebrew...
Already up-to-date.
DEBUG Step "Brew Cask"
DEBUG Detected "/home/claire/.linuxbrew/bin/brew" as "brew"
DEBUG Executing command `/home/claire/.linuxbrew/bin/brew --version`
DEBUG Step "Brew Cask" failed:
   0: \x1b[91mThe output of `brew --version` changed: Invalid version. This is not your fault, this is an issue in Topgrade. Please open an issue at: https://github.com/topgrade-rs/topgrade/issues/new?template=bug_report.md\x1b[0m
   1: \x1b[91munexpected character '>' while parsing major version number\x1b[0m

Location:
   \x1b[35msrc/steps/os/unix.rs\x1b[0m:\x1b[35m395\x1b[0m
Brew Cask failed:
   0: The output of `brew --version` changed: Invalid version. This is not your fault, this is an issue in Topgrade. Please open an issue at: https://github.com/topgrade-rs/topgrade/issues/new?template=bug_report.md
   1: unexpected character '>' while parsing major version number

Location:
   src/steps/os/unix.rs:395
</pre>
</details>

### PR DESCRIPTION
**Pull request by GideonBear**
## What does this PR do
Closes #1599
Ref #904, #1539

## Standards checklist

- [x] The PR title is descriptive
- [x] I have read `CONTRIBUTING.md`
- [ ] *Optional:* I have tested the code myself
- [ ] If this PR introduces new user-facing messages they are translated

### CODE REVIEW

**Comment by GideonBear** [comment]
@Chapien Could you test if this works for you?
`cargo install --git https://github.com/GideonBear/topgrade --branch fix-brew`
`~/.cargo/bin/topgrade --only brew_cask --only brew_formula --verbose`

**Comment by Chapien** [comment]
> @Chapien Could you test if this works for you? `cargo install --git https://github.com/GideonBear/topgrade --branch fix-brew` `~/.cargo/bin/topgrade --only brew_cask --only brew_formula --verbose`

Seems not to work I'm afraid. Now it can't find brew.

```
DEBUG Current system locale is en-US
DEBUG Configuration at /home/claire/.config/topgrade.toml
DEBUG Found additional (directory) configuration file at /home/claire/.config/topgrade.d/config.toml
DEBUG Loaded configuration: ConfigFile { include: Some(Include { paths: None }), misc: Some(Misc { allow_root: None, pre_sudo: None, sudo_command: None, disable: Some([Vcpkg, Yarn, Node, Pip3, Waydroid, Powershell, Composer, Containers, Vscode, Vscodium]), ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, tmux_arguments: None, set_title: None, display_time: None, assume_yes: None, no_retry: None, show_skipped: None, run_in_tmux: None, tmux_session_mode: None, cleanup: None, notify_each_step: None, skip_notify: None, bashit_branch: None, only: None, no_self_update: None, log_filters: None, show_distribution_summary: None }), pre_commands: Some({}), post_commands: Some({}), commands: Some({}), conda: None, python: Some(Python { enable_pip_review: None, enable_pip_review_local: None, enable_pipupgrade: None, pipupgrade_arguments: None, poetry_force_self_update: None }), composer: Some(Composer { self_update: None }), brew: Some(Brew { greedy_cask: None, greedy_latest: None, greedy_auto_updates: None, autoremove: None, fetch_head: None }), linux: Some(Linux { yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, arch_package_manager: None, show_arch_news: None, garuda_update_arguments: None, trizen_arguments: None, pikaur_arguments: None, pamac_arguments: None, dnf_arguments: None, nix_arguments: None, nix_env_arguments: None, apt_arguments: None, enable_tlmgr: None, redhat_distro_sync: None, suse_dup: None, rpm_ostree: None, bootc: None, emerge_sync_flags: None, emerge_update_flags: None, home_manager_arguments: None }), mandb: None, git: Some(Git { max_concurrency: None, arguments: None, repos: None, pull_predefined: None, fetch_only: None }), containers: Some(Containers { ignored_containers: None, runtime: None, system_prune: None }), windows: Some(Windows { accept_all_updates: None, updates_auto_reboot: None, self_rename: None, open_remotes_in_new_terminal: None, wsl_update_pre_release: None, wsl_update_use_web_download: None, winget_silent_install: None, winget_use_sudo: None }), npm: Some(NPM { use_sudo: None }), chezmoi: None, mise: None, yarn: Some(Yarn { use_sudo: None }), deno: Some(Deno { version: None }), vim: Some(Vim { force_plug_update: None }), firmware: Some(Firmware { upgrade: None }), vagrant: Some(Vagrant { directories: None, power_on: None, always_suspend: None }), flatpak: Some(Flatpak { use_sudo: None }), pixi: None, distrobox: Some(Distrobox { use_root: None, containers: None }), lensfun: Some(Lensfun { use_sudo: None }), julia: Some(JuliaConfig { startup_file: None }), zigup: Some(Zigup { target_versions: None, install_dir: None, path_link: None, cleanup: None }), vscode: Some(VscodeConfig { profile: None }), doom: None, rustup: None, pkgfile: None }
DEBUG Version: 16.6.1
DEBUG OS: x86_64-unknown-linux-gnu
DEBUG Args { inner: ["topgrade", "--only", "brew_cask", "--only", "brew_formula", "--verbose"] }
DEBUG Binary path: Ok("/home/claire/.cargo/bin/topgrade")
DEBUG self-update Feature Enabled: false
DEBUG Configuration: Config { opt: CommandLineArgs { edit_config: false, show_config_reference: false, run_in_tmux: false, no_tmux: false, cleanup: false, dry_run: false, run_type: Wet, no_retry: false, disable: [], only: [BrewCask, BrewFormula], custom_commands: [], env: [], verbose: true, keep_at_end: false, skip_notify: false, yes: None, disable_predefined_git_repos: false, config: None, remote_host_limit: None, show_skipped: false, allow_root: false, log_filter: "warn", gen_completion: None, gen_manpage: false, no_self_update: false }, config_file: ConfigFile { include: Some(Include { paths: None }), misc: Some(Misc { allow_root: None, pre_sudo: None, sudo_command: None, disable: Some([Vcpkg, Yarn, Node, Pip3, Waydroid, Powershell, Composer, Containers, Vscode, Vscodium]), ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, tmux_arguments: None, set_title: None, display_time: None, assume_yes: None, no_retry: None, show_skipped: None, run_in_tmux: None, tmux_session_mode: None, cleanup: None, notify_each_step: None, skip_notify: None, bashit_branch: None, only: None, no_self_update: None, log_filters: None, show_distribution_summary: None }), pre_commands: Some({}), post_commands: Some({}), commands: Some({}), conda: None, python: Some(Python { enable_pip_review: None, enable_pip_review_local: None, enable_pipupgrade: None, pipupgrade_arguments: None, poetry_force_self_update: None }), composer: Some(Composer { self_update: None }), brew: Some(Brew { greedy_cask: None, greedy_latest: None, greedy_auto_updates: None, autoremove: None, fetch_head: None }), linux: Some(Linux { yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, arch_package_manager: None, show_arch_news: None, garuda_update_arguments: None, trizen_arguments: None, pikaur_arguments: None, pamac_arguments: None, dnf_arguments: None, nix_arguments: None, nix_env_arguments: None, apt_arguments: None, enable_tlmgr: None, redhat_distro_sync: None, suse_dup: None, rpm_ostree: None, bootc: None, emerge_sync_flags: None, emerge_update_flags: None, home_manager_arguments: None }), mandb: None, git: Some(Git { max_concurrency: None, arguments: None, repos: None, pull_predefined: None, fetch_only: None }), containers: Some(Containers { ignored_containers: None, runtime: None, system_prune: None }), windows: Some(Windows { accept_all_updates: None, updates_auto_reboot: None, self_rename: None, open_remotes_in_new_terminal: None, wsl_update_pre_release: None, wsl_update_use_web_download: None, winget_silent_install: None, winget_use_sudo: None }), npm: Some(NPM { use_sudo: None }), chezmoi: None, mise: None, yarn: Some(Yarn { use_sudo: None }), deno: Some(Deno { version: None }), vim: Some(Vim { force_plug_update: None }), firmware: Some(Firmware { upgrade: None }), vagrant: Some(Vagrant { directories: None, power_on: None, always_suspend: None }), flatpak: Some(Flatpak { use_sudo: None }), pixi: None, distrobox: Some(Distrobox { use_root: None, containers: None }), lensfun: Some(Lensfun { use_sudo: None }), julia: Some(JuliaConfig { startup_file: None }), zigup: Some(Zigup { target_versions: None, install_dir: None, path_link: None, cleanup: None }), vscode: Some(VscodeConfig { profile: None }), doom: None, rustup: None, pkgfile: None }, allowed_steps: [BrewCask, BrewFormula] }
DEBUG Running with euid: 1000
DEBUG Cannot find "doas"
DEBUG Detected "/usr/bin/sudo" as "sudo"
DEBUG Sudo: Ok(Sudo { path: Some("/usr/bin/sudo"), kind: Sudo })
DEBUG Step "Brew"
DEBUG Detected "/home/claire/.linuxbrew/bin/brew" as "brew"
DEBUG linuxbrew_directory owner_id: 951, current_id: 1000

── 15:49:35 - Brew (sudo as user 'linuxbrew') ──────────────────────────────────
DEBUG Executing command `/usr/bin/sudo -H -u linuxbrew brew update`
[sudo] password for claire:
sudo: brew: command not found
DEBUG Command failed: Err(
   0: \x1b[91mCommand failed: `/usr/bin/sudo -H -u linuxbrew brew update`\x1b[0m
   1: \x1b[91m`/usr/bin/sudo` failed: exit status: 1\x1b[0m

Location:
   \x1b[35msrc/steps/os/unix.rs\x1b[0m:\x1b[35m360\x1b[0m)
DEBUG Step "Brew" failed:
   0: \x1b[91mCommand failed: `/usr/bin/sudo -H -u linuxbrew brew update`\x1b[0m
   1: \x1b[91m`/usr/bin/sudo` failed: exit status: 1\x1b[0m

Location:
   \x1b[35msrc/steps/os/unix.rs\x1b[0m:\x1b[35m360\x1b[0m
Brew failed:
   0: Command failed: `/usr/bin/sudo -H -u linuxbrew brew update`
   1: `/usr/bin/sudo` failed: exit status: 1

```

**Comment by GideonBear** [comment]
> Seems not to work I'm afraid. Now it can't find brew.

@Chapien How about now?

**Comment by Chapien** [comment]
> > Seems not to work I'm afraid. Now it can't find brew.
> 
> @Chapien How about now?

Worked, at least for me! Sorry for delays in responding I get distracted easily.

File: src/steps/os/unix.rs [hunk 1]
```diff
@@ -354,29 +377,29 @@ pub fn run_brew_formula(ctx: &ExecutionContext, variant: BrewVariant) -> Result<
...
-    if variant.is_path() && !BrewVariant::is_macos_custom(binary_name) {
+    if variant.is_path() && !brew.is_macos_custom() {
         return Err(SkipStep(t!("Not a custom brew for macOS").to_string()).into());
     }
 
     #[cfg(target_os = "linux")]
     {
         // Homebrew cask support was added in version 4.5.0
-        let version_output = Command::new(&binary_name).arg("--version").output_checked_utf8()?;
+        let version_output = brew.execute(ctx)?.arg("--version").output_checked_utf8()?;
```
Comment (GideonBear) [inline src/steps/os/unix.rs:403]:
```suggestion
        // TODO: This should run even when dry-running. Blocked by #1227.
        let version_output = brew.execute(ctx)?.arg("--version").output_checked_utf8()?;
```

**Comment by GideonBear** [comment]
> Worked, at least for me! Sorry for delays in responding I get distracted easily.

No worries, thanks for checking!
