### PR TITLE
Fix issue with RubyGems update command

### LINKED ISSUE #247: RubyGems fails
## What did you expect to happen?

I would expect topgrade to upgrade everything flawlessyl, as usual

## What actually happened?

Since few days, I get an error while upgrading gem

<details>
<summary>output</summary>

```
―― 20:26:54 - RubyGems ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
ERROR:  While executing gem ... (Gem::UnknownCommandError)
    Unknown command update --system
	/Users/loranger/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/command_manager.rb:198:in `find_command'
	/Users/loranger/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/command_manager.rb:183:in `process_args'
	/Users/loranger/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/command_manager.rb:149:in `run'
	/Users/loranger/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/gem_runner.rb:51:in `run'
	/Users/loranger/.rubies/ruby-3.1.0/bin/gem:13:in `<main>'
rubygems failed:
   0: Command failed: `/Users/loranger/.rubies/ruby-3.1.0/bin/gem 'update --system' --user-install`
   1: `/Users/loranger/.rubies/ruby-3.1.0/bin/gem` failed: exit status: 1

Location:
   src/steps/generic.rs:100

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Retry? (y)es/(N)o/(s)hell/(q)uit
```

</details>

## Additional Details
- OS: macOS Ventura 13.0.1
- Topgrade installed via brew
- Topgrade 10.2.1

<details>
<summary>topgrade --dry-run</summary>

```
―― 20:33:23 - Brew ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Dry running: /opt/homebrew/bin/brew update
Dry running: /opt/homebrew/bin/brew upgrade --ignore-pinned --formula

―― 20:33:23 - Brew - Cask ――――――――――――――――――――――――――――――――――――――――――――――――――――――
Dry running: /opt/homebrew/bin/brew upgrade --cask

―― 20:33:24 - Git repositories ―――――――――――――――――――――――――――――――――――――――――――――――――
Would pull /Users/loranger/.zprezto

―― 20:33:24 - pip3 ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Dry running: /opt/homebrew/bin/python3 -m pip install --upgrade --user pip

―― 20:33:24 - Node Package Manager ―――――――――――――――――――――――――――――――――――――――――――――
Dry running: /opt/homebrew/bin/npm update '--location=global'

―― 20:33:25 - Composer ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Dry running: /opt/homebrew/bin/composer global update

―― 20:33:25 - Gems ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Dry running: /Users/loranger/.rubies/ruby-3.1.0/bin/gem update --user-install

―― 20:33:25 - RubyGems ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Dry running: /Users/loranger/.rubies/ruby-3.1.0/bin/gem 'update --system' --user-install

―― 20:33:25 - Local Nextcloud Apps (docker) ――――――――――――――――――――――――――――――――――――
Dry running: /bin/zsh -c 'ssh rock.local '\''docker-compose -f /home/loranger/nextcloud/docker-compose.yml run --rm occ app:update --all'\'''

―― 20:33:25 - Nextcloud (ansible) ――――――――――――――――――――――――――――――――――――――――――――――
Dry running: /bin/zsh -c 'ansible nextcloud -m shell -a '\''php /var/www/nextcloud/updater/updater.phar --no-interaction'\'' --become --become-user nextcloud'

―― 20:33:25 - Nextcloud Apps (ansible) ―――――――――――――――――――――――――――――――――――――――――
Dry running: /bin/zsh -c 'ansible nextcloud -m shell -a '\''php /var/www/nextcloud/occ app:update --all'\'' --become --become-user nextcloud'

―― 20:33:25 - macOS App Store ――――――――――――――――――――――――――――――――――――――――――――――――――
Dry running: /opt/homebrew/bin/mas upgrade

―― 20:33:25 - macOS system update ――――――――――――――――――――――――――――――――――――――――――――――
Finding available software
No new software available.

―― 20:33:28 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Brew (ARM): OK
Brew Cask (ARM): OK
Git repositories: OK
pip3: OK
npm: OK
composer: OK
gem: OK
rubygems: OK
Local Nextcloud Apps (docker): OK
Nextcloud (ansible): OK
Nextcloud Apps (ansible): OK
App Store: OK
System upgrade: OK
```
</details>

<details>
<summary>topgrade -v</summary>

```
(...)
DEBUG Step "krew"
DEBUG Step "gem"
DEBUG Detected "/Users/loranger/.rubies/ruby-3.1.0/bin/gem" as "gem"
DEBUG Path "/Users/loranger/.gem" exists

―― 20:35:52 - Gems ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
DEBUG Detected rbenv. Avoiding --user-install
DEBUG Executing command `/Users/loranger/.rubies/ruby-3.1.0/bin/gem update --user-install`
Updating installed gems
Nothing to update
DEBUG Step "rubygems"
DEBUG Detected "/Users/loranger/.rubies/ruby-3.1.0/bin/gem" as "gem"
DEBUG Path "/Users/loranger/.gem" exists

―― 20:35:54 - RubyGems ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
DEBUG Detected rbenv. Avoiding --user-install
DEBUG Executing command `/Users/loranger/.rubies/ruby-3.1.0/bin/gem 'update --system' --user-install`
ERROR:  While executing gem ... (Gem::UnknownCommandError)
    Unknown command update --system
	/Users/loranger/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/command_manager.rb:198:in `find_command'
	/Users/loranger/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/command_manager.rb:183:in `process_args'
	/Users/loranger/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/command_manager.rb:149:in `run'
	/Users/loranger/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/gem_runner.rb:51:in `run'
	/Users/loranger/.rubies/ruby-3.1.0/bin/gem:13:in `<main>'
DEBUG Command failed: Err(
   0: Command failed: `/Users/loranger/.rubies/ruby-3.1.0/bin/gem 'update --system' --user-install`
   1: `/Users/loranger/.rubies/ruby-3.1.0/bin/gem` failed: exit status: 1

Location:
   src/steps/generic.rs:100

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.)
DEBUG Step "rubygems" failed:
   0: Command failed: `/Users/loranger/.rubies/ruby-3.1.0/bin/gem 'update --system' --user-install`
   1: `/Users/loranger/.rubies/ruby-3.1.0/bin/gem` failed: exit status: 1

Location:
   src/steps/generic.rs:100

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
rubygems failed:
   0: Command failed: `/Users/loranger/.rubies/ruby-3.1.0/bin/gem 'update --system' --user-install`
   1: `/Users/loranger/.rubies/ruby-3.1.0/bin/gem` failed: exit status: 1

Location:
   src/steps/generic.rs:100

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.DEBUG Desktop notification: rubygems failed

Retry? (y)es/(N)o/(s)hell/(q)uit
```

</details>

<details>
<summary>RUST_BACKTRACE=1 topgrade --only ruby_gems</summary>

```
―― 20:41:17 - RubyGems ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
ERROR:  While executing gem ... (Gem::UnknownCommandError)
    Unknown command update --system
	/Users/loranger/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/command_manager.rb:198:in `find_command'
	/Users/loranger/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/command_manager.rb:183:in `process_args'
	/Users/loranger/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/command_manager.rb:149:in `run'
	/Users/loranger/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/gem_runner.rb:51:in `run'
	/Users/loranger/.rubies/ruby-3.1.0/bin/gem:13:in `<main>'
rubygems failed:
   0: Command failed: `/Users/loranger/.rubies/ruby-3.1.0/bin/gem 'update --system' --user-install`
   1: `/Users/loranger/.rubies/ruby-3.1.0/bin/gem` failed: exit status: 1

Location:
   src/steps/generic.rs:100

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 2 frames hidden ⋮
   3: <E as eyre::context::ext::StdError>::ext_report::h3914eb7fca7d3c7e
      at <unknown source file>:<unknown line>
   4: <std::process::Command as topgrade::command::CommandExt>::status_checked_with::h5f958d61cee44d75
      at <unknown source file>:<unknown line>
   5: topgrade::runner::Runner::execute::hc5a7673ee7c1f2ee
      at <unknown source file>:<unknown line>
   6: topgrade::run::h3c67bc3f7c3790f8
      at <unknown source file>:<unknown line>
   7: topgrade::main::hc6c76f70bcfed8aa
      at <unknown source file>:<unknown line>
   8: std::sys_common::backtrace::__rust_begin_short_backtrace::he9796edb044ece37
      at <unknown source file>:<unknown line>
   9: _main<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
Retry? (y)es/(N)o/(s)hell/(q)uit
```

</details>

<details>
<summary>gem update --system --user-install</summary>

```
$ gem update --system --user-install
Latest version already installed. Done.
```

</details>

### PR DESCRIPTION
**Pull request by rm3l**
Hi there,

I just ran into the same issue reported in #247, and created this PR to fix it.
Since this is my very first PR in this repo, please let me know if things should be done differently.

Per the [instructions in the README](https://github.com/topgrade-rs/topgrade#contribution-guidelines), I tried to create a PR against the `bug-fixes` branch instead, but it looks like there is no such branch.

Fixes #247

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The code compiles (`cargo build`)
- [x] The code passes rustfmt (`cargo fmt`)
- [x] The code passes clippy (`cargo clippy`)
- [x] The code passes tests (`cargo test`)
- [x] *Optional:* I have tested the code myself
    - [x] I also tested that Topgrade skips the step where needed

~If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.~

### CODE REVIEW

File: src/steps/generic.rs [hunk 1]
```diff
@@ -90,7 +90,7 @@ pub fn run_rubygems(base_dirs: &BaseDirs, run_type: RunType) -> Result<()> {
     print_separator("RubyGems");
 
     let mut command = run_type.execute(gem);
-    command.arg("update --system");
+    command.args(["update", "--system"]);
 
     if env::var_os("RBENV_SHELL").is_none() {
         debug!("Detected rbenv. Avoiding --user-install");
```
Comment (mouse07410) [inline src/steps/generic.rs:96]: Either I'm still cranky form my cold, or this line does not make sense. Or it's totally in a wrong place.

**Review by mouse07410 — APPROVED** [review]
This is a good and necessary fix. I hope it's merged soon.

I hope somebody would take care of the line 96 too.

File: src/steps/generic.rs (hunk 1 above)
Comment (DottoDev) [reply src/steps/generic.rs:96]: This does make sense because this informant doesn't have to be displayed when run in default mode.

**Review by DottoDev — APPROVED** [review]

File: src/steps/generic.rs (hunk 1 above)
Comment (mouse07410) [reply src/steps/generic.rs:96]: @DottoDev I said the statement does not make sense because it's within the `if` block that's triggered when there is **no RBENV**, aka - no `RBENV_SHELL` env var set. More so, the statement says `**avoiding** --user-install`, while in fact `--user-install` **is** added to the command invocation.

Unless I'm misreading this code,  this block should look like
```rs
if env::var_os("RBENV_SHELL").is_none() {
        command.arg("--user-install");
        debug!("Did not detect rbenv. Adding --user-install");
} else {
        debug!("Detected rbenv. Avoiding --user-install");
}
```

Comment (rm3l) [reply src/steps/generic.rs:96]: Indeed, the message logged seems misleading..
If you prefer, I can also mark this conversation as resolved and immediately open up a separate PR with what you suggested, @mouse07410 ..

Comment (DottoDev) [reply src/steps/generic.rs:96]: @mouse07410 you are right, it does the opposite of what it's supposed to do.

Comment (mouse07410) [reply src/steps/generic.rs:96]: > Indeed, the message logged seems misleading..
> 
> If you prefer, I can also mark this conversation as resolved and immediately open up a separate PR with what you suggested, @mouse07410 ..

Yes please! This would be the best course. Thank you!

Comment (DottoDev) [reply src/steps/generic.rs:96]: Marked as resolved for merging

Comment (rm3l) [reply src/steps/generic.rs:96]: > > Indeed, the message logged seems misleading..
> > If you prefer, I can also mark this conversation as resolved and immediately open up a separate PR with what you suggested, @mouse07410 ..
> 
> Yes please! This would be the best course. Thank you!

Just created https://github.com/topgrade-rs/topgrade/pull/249 based on your suggestions.
