### PR TITLE
Fix vscodium skipping silently

### LINKED ISSUE #1108: Vscodium "Too old vscodium version to have update extensions command" on latest version (1.99.02289)
## Erroneous Behavior

```
DEBUG Step "VSCodium extensions"
DEBUG Executing command `uname -r`
DEBUG Uname output: 6.8.0-57-generic

DEBUG Detected "/usr/bin/codium" as "codium"
DEBUG Executing command `/usr/bin/codium --version`

── 15:00:55 - Summary ──────────────────────────────────────────────────────────
VSCodium extensions: SKIPPED: Too old vscodium version to have update extensions command
```

## Expected Behavior

The version should be parsed correctly

## Steps to reproduce

`codium --version`:
```
1.99.02289
d033c221592da47b4d3ea04e23a8d1ec6d8b7333
x64
```

```bash
topgrade --only vscodium -v
```

## Possible Cause (Optional)

```
[src/steps/generic.rs:441:9] version = Err(
    Error("invalid leading zero in patch version number"),
)
```
Two things that need to be fixed:
1. When the version is incorrectly parsed (is `Err(_)`), instead of assuming the version is too old, throw it as an error. This way these issues do not go unnoticed; the step now just got skipped which made the issue invisible
2. Allow leading zero in patch version number when parsing version

## Additional Details
- Operation System/Version
  

- Installation
  
`cargo run` on `main`

- Topgrade version (`topgrade -V`)
16.0.3 (`main`)

## Verbose Output (`topgrade -v`)

<details>
<pre>
DEBUG Current system locale is en-US
DEBUG Configuration at /home/gideon/.config/topgrade.toml
DEBUG Loaded configuration: ConfigFile { include: Some(Include { paths: None }), misc: Some(Misc { pre_sudo: None, sudo_command: None, disable: None, ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, tmux_arguments: None, set_title: Some(false), display_time: None, assume_yes: None, no_retry: None, run_in_tmux: None, tmux_session_mode: None, cleanup: None, notify_each_step: None, skip_notify: None, bashit_branch: None, only: None, no_self_update: None, log_filters: None }), pre_commands: Some({}), post_commands: Some({}), commands: Some({}), python: Some(Python { enable_pip_review: None, enable_pip_review_local: None, enable_pipupgrade: None, pipupgrade_arguments: None, poetry_force_self_update: None }), composer: Some(Composer { self_update: None }), brew: Some(Brew { greedy_cask: None, greedy_latest: None, greedy_auto_updates: None, autoremove: None, fetch_head: None }), linux: Some(Linux { yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, arch_package_manager: None, show_arch_news: None, garuda_update_arguments: None, trizen_arguments: None, pikaur_arguments: None, pamac_arguments: None, dnf_arguments: None, nix_arguments: None, nix_env_arguments: None, apt_arguments: None, enable_tlmgr: None, redhat_distro_sync: None, suse_dup: None, rpm_ostree: None, bootc: None, emerge_sync_flags: None, emerge_update_flags: None, home_manager_arguments: None }), git: Some(Git { max_concurrency: None, arguments: None, repos: None, pull_predefined: None }), containers: Some(Containers { ignored_containers: None, runtime: None }), windows: Some(Windows { accept_all_updates: None, self_rename: None, open_remotes_in_new_terminal: None, wsl_update_pre_release: None, wsl_update_use_web_download: None, winget_silent_install: None }), npm: Some(NPM { use_sudo: None }), yarn: Some(Yarn { use_sudo: None }), deno: None, vim: Some(Vim { force_plug_update: None }), firmware: Some(Firmware { upgrade: None }), vagrant: Some(Vagrant { directories: None, power_on: None, always_suspend: None }), flatpak: Some(Flatpak { use_sudo: None }), distrobox: Some(Distrobox { use_root: None, containers: None }), lensfun: Some(Lensfun { use_sudo: None }), julia: None, zigup: None, vscode: None }
DEBUG Version: 16.0.3
DEBUG OS: x86_64-unknown-linux-gnu
DEBUG Args { inner: ["target/debug/topgrade", "--only", "vscodium", "-v"] }
DEBUG Binary path: Ok("/home/gideon/projects/topgrade/target/debug/topgrade")
DEBUG self-update Feature Enabled: false
DEBUG Configuration: Config { opt: CommandLineArgs { edit_config: false, show_config_reference: false, run_in_tmux: false, cleanup: false, dry_run: false, no_retry: false, disable: [], only: [Vscodium], custom_commands: [], env: [], verbose: true, keep_at_end: false, skip_notify: false, yes: None, disable_predefined_git_repos: false, config: None, remote_host_limit: None, show_skipped: false, log_filter: "warn", gen_completion: None, gen_manpage: false, no_self_update: false }, config_file: ConfigFile { include: Some(Include { paths: None }), misc: Some(Misc { pre_sudo: None, sudo_command: None, disable: None, ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, tmux_arguments: None, set_title: Some(false), display_time: None, assume_yes: None, no_retry: None, run_in_tmux: None, tmux_session_mode: None, cleanup: None, notify_each_step: None, skip_notify: None, bashit_branch: None, only: None, no_self_update: None, log_filters: None }), pre_commands: Some({}), post_commands: Some({}), commands: Some({}), python: Some(Python { enable_pip_review: None, enable_pip_review_local: None, enable_pipupgrade: None, pipupgrade_arguments: None, poetry_force_self_update: None }), composer: Some(Composer { self_update: None }), brew: Some(Brew { greedy_cask: None, greedy_latest: None, greedy_auto_updates: None, autoremove: None, fetch_head: None }), linux: Some(Linux { yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, arch_package_manager: None, show_arch_news: None, garuda_update_arguments: None, trizen_arguments: None, pikaur_arguments: None, pamac_arguments: None, dnf_arguments: None, nix_arguments: None, nix_env_arguments: None, apt_arguments: None, enable_tlmgr: None, redhat_distro_sync: None, suse_dup: None, rpm_ostree: None, bootc: None, emerge_sync_flags: None, emerge_update_flags: None, home_manager_arguments: None }), git: Some(Git { max_concurrency: None, arguments: None, repos: None, pull_predefined: None }), containers: Some(Containers { ignored_containers: None, runtime: None }), windows: Some(Windows { accept_all_updates: None, self_rename: None, open_remotes_in_new_terminal: None, wsl_update_pre_release: None, wsl_update_use_web_download: None, winget_silent_install: None }), npm: Some(NPM { use_sudo: None }), yarn: Some(Yarn { use_sudo: None }), deno: None, vim: Some(Vim { force_plug_update: None }), firmware: Some(Firmware { upgrade: None }), vagrant: Some(Vagrant { directories: None, power_on: None, always_suspend: None }), flatpak: Some(Flatpak { use_sudo: None }), distrobox: Some(Distrobox { use_root: None, containers: None }), lensfun: Some(Lensfun { use_sudo: None }), julia: None, zigup: None, vscode: None }, allowed_steps: [Vscodium] }
DEBUG Cannot find "pwsh"
DEBUG Cannot find "powershell"
DEBUG Path "/home/gideon/.config/emacs" doesn't exist
DEBUG Path "/home/gideon/.emacs.d" doesn't exist
DEBUG Cannot find "doas"
DEBUG Detected "/usr/bin/sudo" as "sudo"
DEBUG Cannot find "gsudo"
DEBUG Step "VSCodium extensions"
DEBUG Executing command `uname -r`
DEBUG Uname output: 6.8.0-57-generic

DEBUG Detected "/usr/bin/codium" as "codium"
DEBUG Executing command `/usr/bin/codium --version`
[src/steps/generic.rs:441:9] version = Err(
    Error("invalid leading zero in patch version number"),
)

── 15:05:47 - Summary ──────────────────────────────────────────────────────────
VSCodium extensions: SKIPPED: Too old vscodium version to have update extensions command
DEBUG Desktop notification: Topgrade finished successfully
</pre>
</details>

### PR DESCRIPTION
**Pull request by GideonBear**
Closes #1108

## What does this PR do
* When the version is incorrectly parsed (is Err(_)), instead of assuming the version is too old, throw it as an error. This way these issues do not go unnoticed; the step now just got skipped which made the issue invisible.
  * As mentioned in the comments: "The benefit of handling VSCodium versions so old that the version format is something unexpected is outweighed by the benefit of failing fast on new breaking versions"
* Allow leading zero in patch version number when parsing version, by stripping these before passing it to `semver` (which explicitly does not support leading zeroes, because the SemVer spec does not allow them)
* Fixes minor error in comments

## Standards checklist

- [x] The PR title is descriptive
- [x] I have read `CONTRIBUTING.md`
- [x] *Optional:* I have tested the code myself
- [ ] If this PR introduces new user-facing messages they are translated

### CODE REVIEW

File: src/steps/generic.rs [hunk 1]
```diff
@@ -433,11 +433,25 @@ pub fn run_vscodium_extensions_update(ctx: &ExecutionContext) -> Result<()> {
         .lines()
         .next()
     {
-        Some(item) => Version::parse(item).map_err(std::convert::Into::into),
+        Some(item) => {
+            // Strip leading zeroes because `semver` does not allow them, but VSCodium uses them sometimes
```
Comment (SteveLauC) [inline src/steps/generic.rs:437]: Is this exclusive to VSCodium or is it also present in VSCode as well?

File: src/steps/generic.rs [hunk 2]
```diff
@@ -433,11 +433,25 @@ pub fn run_vscodium_extensions_update(ctx: &ExecutionContext) -> Result<()> {
...
+            Version::parse(&item).map_err(std::convert::Into::into)
+        }
         _ => return Err(SkipStep(String::from("Cannot find vscodium version")).into()),
     };
 
-    if !matches!(version, Ok(version) if version >= Version::new(1, 86, 0)) {
+    // Raise any errors in parsing the version
+    //  The benefit of handling VSCodium versions so old that the version format is something
+    //  unexpected is outweighed by the benefit of failing fast on new breaking versions
+    let version = version.wrap_err("the output of `codium --version` changed, please file an issue to Topgrade")?;
```
Comment (SteveLauC) [inline src/steps/generic.rs:451]: > When the version is incorrectly parsed (is Err(_)), instead of assuming the version is too old, throw it as an error. 

I think we should port this to the VSCode step as well

Comment (SteveLauC) [reply src/steps/generic.rs:451]: There are only 2 steps, so it is ok to allow a tiny amount of duplications, IMHO

Comment (GideonBear) [reply src/steps/generic.rs:451]: IMO the fact that I forgot to apply it to the other as well proves that its better to deduplicate it. Especially now that it gets more complex with the zero stripping. But if you want I'll keep it this way.

Comment (SteveLauC) [reply src/steps/generic.rs:451]: You can try it in a commit, and if we are not overengineering:

1. Allow incompatible changes between VSCode and VSCodium
2. The whole thing is still easy to understand and maintain

I will accept it

File: src/steps/generic.rs (hunk 1 above)
Comment (GideonBear) [reply src/steps/generic.rs:437]: This is not present in VSCode. But I'll include it in the generic function anyway; I don't think it can cause any harm.

**Comment by GideonBear** [comment]
```rust
_ => return Err(SkipStep(format!("Cannot find {name} version")).into()),
```
@SteveLauC Is there a reason to skip silently when `code --version` fails? Can we propagate the error in this case as well?

**Comment by SteveLauC** [comment]
> @SteveLauC Is there a reason to skip silently when code --version has unexpected output? Can we propagate the error in this case as well?

I think we should error out rather than skipping the step

File: src/steps/generic.rs [hunk 3]
```diff
@@ -410,88 +410,82 @@ pub fn run_vcpkg_update(ctx: &ExecutionContext) -> Result<()> {
...
-
-    ctx.run_type()
-        .execute(vscodium)
-        .arg("--update-extensions")
-        .status_checked()
-}
+    // Raise any errors in parsing the version
+    //  The benefit of handling VSCodium versions so old that the version format is something
+    //  unexpected is outweighed by the benefit of failing fast on new breaking versions
+    let version = version.wrap_err(format!(
```
Comment (SteveLauC) [inline src/steps/generic.rs:451]: We can use your `output_changed_message!()` macro here, let's me merge this PR first, then you can rebase your `GideonBear:remove-expects` branch to get this updated

File: src/steps/generic.rs [hunk 4]
```diff
@@ -410,88 +410,82 @@ pub fn run_vcpkg_update(ctx: &ExecutionContext) -> Result<()> {
...
+            // Strip leading zeroes because `semver` does not allow them, but VSCodium uses them sometimes.
+            //  This is not the case for VSCode, but just in case, and it can't really cause any issues.
+            let item = item
+                .split('.')
+                .map(|s| s.trim_start_matches('0'))
+                .collect::<Vec<_>>()
+                .join(".");
+            Version::parse(&item).map_err(std::convert::Into::into)
+        }
+        None => return Err(SkipStep(format!("Cannot find {name} version")).into()),
```
Comment (SteveLauC) [inline src/steps/generic.rs:445]: > > @SteveLauC Is there a reason to skip silently when code --version has unexpected output? Can we propagate the error in this case as well?
>
> I think we should error out rather than skipping the step

Let's return an error here, something similar to the one down below

**Comment by GideonBear** [comment]
Whoops. Thought about this pretty important edge case!

File: src/steps/generic.rs (hunk 4 above)
Comment (GideonBear) [reply src/steps/generic.rs]: Done!

File: src/steps/generic.rs (hunk 3 above)
Comment (GideonBear) [reply src/steps/generic.rs:451]: :+1:

**Review by SteveLauC — APPROVED** [review]
Thanks!

File: src/steps/generic.rs (hunk 3 above)
Comment (GideonBear) [reply src/steps/generic.rs:484]: Done!
