### PR TITLE
Fix `uv` step

### LINKED ISSUE #1120: Broken `uv` self updating since #1105
## Erroneous Behavior

```
The application panicked (crashed).
Message:  the output of `uv --version` changed, please file an issue to Topgrade
Location: src/steps/generic.rs:1302
```

## Expected Behavior

Updating `uv` like it did for me before

## Steps to reproduce

1. Install uv: `curl -LsSf https://astral.sh/uv/install.sh | sh`
2. Make sure you're on the main branch of Topgrade that includes PR #1105
3. `cargo run -- --only uv`

## Possible Cause (Optional)

#1105 expects `uv 0.5.11 (c4d0caaee 2024-12-19)\n`, while my `uv --version` output is `uv 0.6.14\n`.

## Problem persists without calling from topgrade

- [ ] Yes
- [x] No

## Did you run topgrade through `Remote Execution`

- [ ] Yes
- [x] No

## Configuration file (Optional)

N/A

## Additional Details
- Operation System/Version
  
N/A

- Installation
  
Build `main` branch from source

- Topgrade version (`topgrade -V`)
- topgrade 16.0.3
- (`main` branch)

## Verbose Output (`topgrade -v`)

<details>
<pre>
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/topgrade --only uv -v`
DEBUG Current system locale is en-US
DEBUG Configuration at /home/gideon/.config/topgrade.toml
DEBUG Path ~/yt-dlp expanded to /home/gideon/yt-dlp
DEBUG Path ~/youtube-dl expanded to /home/gideon/youtube-dl
DEBUG Loaded configuration: ConfigFile { include: Some(Include { paths: None }), misc: Some(Misc { pre_sudo: Some(false), sudo_command: None, disable: None, ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, tmux_arguments: None, set_title: Some(false), display_time: None, assume_yes: Some(true), no_retry: None, run_in_tmux: None, tmux_session_mode: None, cleanup: Some(true), notify_each_step: None, skip_notify: None, bashit_branch: None, only: None, no_self_update: None, log_filters: None }), pre_commands: Some({}), post_commands: Some({}), commands: Some({"Clean JetBrains Toolbox download cache": "if [[ -e '~/.cache/JetBrains/Toolbox/download' ]]; then trash ~/.cache/JetBrains/Toolbox/download -v; fi", "Clean journalctl logs older than 7 days": "sudo journalctl --vacuum-time=7d", "Clean trash older than 30 days": "trash-empty 30 -fv", "Homeupdate": "cd ~/homesync && git pull && bash setup_homesync.sh", "Update venvs": "source ~/.bash_aliases; for file in /home/gideon/projects/*; do cd $file || exit; if [[ -e '.venv' ]]; then source .venv/bin/activate; update_venv; fi; done"}), python: Some(Python { enable_pip_review: None, enable_pip_review_local: None, enable_pipupgrade: None, pipupgrade_arguments: None, poetry_force_self_update: None }), composer: Some(Composer { self_update: None }), brew: Some(Brew { greedy_cask: None, greedy_latest: None, greedy_auto_updates: None, autoremove: None, fetch_head: None }), linux: Some(Linux { yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, arch_package_manager: None, show_arch_news: None, garuda_update_arguments: None, trizen_arguments: None, pikaur_arguments: None, pamac_arguments: None, dnf_arguments: None, nix_arguments: None, nix_env_arguments: None, apt_arguments: None, enable_tlmgr: None, redhat_distro_sync: None, suse_dup: None, rpm_ostree: None, bootc: None, emerge_sync_flags: None, emerge_update_flags: None, home_manager_arguments: None }), git: Some(Git { max_concurrency: None, arguments: None, repos: Some(["/home/gideon/yt-dlp", "/home/gideon/youtube-dl"]), pull_predefined: None }), containers: Some(Containers { ignored_containers: None, runtime: None }), windows: Some(Windows { accept_all_updates: None, self_rename: None, open_remotes_in_new_terminal: None, wsl_update_pre_release: None, wsl_update_use_web_download: None, winget_silent_install: None }), npm: Some(NPM { use_sudo: None }), yarn: Some(Yarn { use_sudo: None }), deno: None, vim: Some(Vim { force_plug_update: None }), firmware: Some(Firmware { upgrade: None }), vagrant: Some(Vagrant { directories: None, power_on: None, always_suspend: None }), flatpak: Some(Flatpak { use_sudo: None }), distrobox: Some(Distrobox { use_root: None, containers: None }), lensfun: Some(Lensfun { use_sudo: None }), julia: None, zigup: None, vscode: None }
DEBUG Version: 16.0.3
DEBUG OS: x86_64-unknown-linux-gnu
DEBUG Args { inner: ["target/debug/topgrade", "--only", "uv", "-v"] }
DEBUG Binary path: Ok("/home/gideon/projects/topgrade/target/debug/topgrade")
DEBUG self-update Feature Enabled: false
DEBUG Configuration: Config { opt: CommandLineArgs { edit_config: false, show_config_reference: false, run_in_tmux: false, cleanup: false, dry_run: false, no_retry: false, disable: [], only: [Uv], custom_commands: [], env: [], verbose: true, keep_at_end: false, skip_notify: false, yes: None, disable_predefined_git_repos: false, config: None, remote_host_limit: None, show_skipped: false, log_filter: "warn", gen_completion: None, gen_manpage: false, no_self_update: false }, config_file: ConfigFile { include: Some(Include { paths: None }), misc: Some(Misc { pre_sudo: Some(false), sudo_command: None, disable: None, ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, tmux_arguments: None, set_title: Some(false), display_time: None, assume_yes: Some(true), no_retry: None, run_in_tmux: None, tmux_session_mode: None, cleanup: Some(true), notify_each_step: None, skip_notify: None, bashit_branch: None, only: None, no_self_update: None, log_filters: None }), pre_commands: Some({}), post_commands: Some({}), commands: Some({"Clean JetBrains Toolbox download cache": "if [[ -e '~/.cache/JetBrains/Toolbox/download' ]]; then trash ~/.cache/JetBrains/Toolbox/download -v; fi", "Clean journalctl logs older than 7 days": "sudo journalctl --vacuum-time=7d", "Clean trash older than 30 days": "trash-empty 30 -fv", "Homeupdate": "cd ~/homesync && git pull && bash setup_homesync.sh", "Update venvs": "source ~/.bash_aliases; for file in /home/gideon/projects/*; do cd $file || exit; if [[ -e '.venv' ]]; then source .venv/bin/activate; update_venv; fi; done"}), python: Some(Python { enable_pip_review: None, enable_pip_review_local: None, enable_pipupgrade: None, pipupgrade_arguments: None, poetry_force_self_update: None }), composer: Some(Composer { self_update: None }), brew: Some(Brew { greedy_cask: None, greedy_latest: None, greedy_auto_updates: None, autoremove: None, fetch_head: None }), linux: Some(Linux { yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, arch_package_manager: None, show_arch_news: None, garuda_update_arguments: None, trizen_arguments: None, pikaur_arguments: None, pamac_arguments: None, dnf_arguments: None, nix_arguments: None, nix_env_arguments: None, apt_arguments: None, enable_tlmgr: None, redhat_distro_sync: None, suse_dup: None, rpm_ostree: None, bootc: None, emerge_sync_flags: None, emerge_update_flags: None, home_manager_arguments: None }), git: Some(Git { max_concurrency: None, arguments: None, repos: Some(["/home/gideon/yt-dlp", "/home/gideon/youtube-dl"]), pull_predefined: None }), containers: Some(Containers { ignored_containers: None, runtime: None }), windows: Some(Windows { accept_all_updates: None, self_rename: None, open_remotes_in_new_terminal: None, wsl_update_pre_release: None, wsl_update_use_web_download: None, winget_silent_install: None }), npm: Some(NPM { use_sudo: None }), yarn: Some(Yarn { use_sudo: None }), deno: None, vim: Some(Vim { force_plug_update: None }), firmware: Some(Firmware { upgrade: None }), vagrant: Some(Vagrant { directories: None, power_on: None, always_suspend: None }), flatpak: Some(Flatpak { use_sudo: None }), distrobox: Some(Distrobox { use_root: None, containers: None }), lensfun: Some(Lensfun { use_sudo: None }), julia: None, zigup: None, vscode: None }, allowed_steps: [Uv] }
DEBUG Cannot find "pwsh"
DEBUG Cannot find "powershell"
DEBUG Path "/home/gideon/.config/emacs" doesn't exist
DEBUG Path "/home/gideon/.emacs.d" doesn't exist
DEBUG Cannot find "doas"
DEBUG Detected "/usr/bin/sudo" as "sudo"
DEBUG Cannot find "gsudo"
DEBUG Step "uv"
DEBUG Detected "/home/gideon/.local/bin/uv" as "uv"

── 15:07:55 - uv ───────────────────────────────────────────────────────────────
DEBUG Executing command `/home/gideon/.local/bin/uv --version`
The application panicked (crashed).
Message:  the output of `uv --version` changed, please file an issue to Topgrade
Location: src/steps/generic.rs:1302
</pre>
</details>

### PR DESCRIPTION
**Pull request by GideonBear**
## What does this PR do
Allows the version format `"uv 0.6.14\n"` as well as `"uv 0.5.11 (c4d0caaee 2024-12-19)\n"`.
Closes #1120.
The problem #1105 solved should be unaffected.

## Standards checklist

- [x] The PR title is descriptive
- [x] I have read `CONTRIBUTING.md`
- [x] *Optional:* I have tested the code myself
- [ ] If this PR introduces new user-facing messages they are translated

### CODE REVIEW

File: src/steps/generic.rs [hunk 1]
```diff
@@ -1318,20 +1318,21 @@ pub fn run_uv(ctx: &ExecutionContext) -> Result<()> {
         .execute(&uv_exec)
         .arg("--version")
         .output_checked_utf8()?;
-    // example output: "uv 0.5.11 (c4d0caaee 2024-12-19)\n"
+    // Multiple possible output formats are possible. For example:
+    //  "uv 0.5.11 (c4d0caaee 2024-12-19)\n"
+    //  "uv 0.6.14\n"
```
Comment (SteveLauC) [inline src/steps/generic.rs:1323]: Thanks for catching this issue!

From uv [source code](https://github.com/astral-sh/uv/blob/6b7f60c1eaa840c2e933a0fb056ab46f99c991a5/crates/uv-cli/src/version.rs#L28-L42), there is another case:

```text
uv 0.5.11+1 (hash date)
```

`semer::Version::parse()` can handle it, so we do not need to change our code:

```rust
use semver::Version;

let version1= Version::parse("0.5.11+1").unwrap();
let version2 = Version::parse("0.5.11").unwrap();

assert!(version1 > version2);
```

And `version1` is greater than `version2`, considering that this number (# of commits) will be greater than 0, this ordering is semantically correct.

Let's just update our code comments to reflect this case:

```suggestion
    // Multiple possible output formats are possible according to uv source code
    //
    // https://github.com/astral-sh/uv/blob/6b7f60c1eaa840c2e933a0fb056ab46f99c991a5/crates/uv-cli/src/version.rs#L28-L42
    //
    // For example:
    //  "uv 0.5.11 (c4d0caaee 2024-12-19)\n"
    //  "uv 0.5.11+1 (xxxd0cee 2024-12-20)\n"
    //  "uv 0.6.14\n"
    
```

File: src/steps/generic.rs [hunk 2]
```diff
@@ -1318,20 +1318,21 @@ pub fn run_uv(ctx: &ExecutionContext) -> Result<()> {
...
-        let first_whitespace_index = start_trimmed
-            .find(' ')
-            .expect("the output of `uv --version` changed, please file an issue to Topgrade");
-        // this should be our version str "0.5.11"
-        &start_trimmed[..first_whitespace_index]
+        // Remove the tailing part " (c4d0caaee 2024-12-19)\n", if it's there
+        match start_trimmed.find(' ') {
+            None => start_trimmed.trim_end_matches('\n'), // Otherwise, just strip the newline
+            Some(i) => &start_trimmed[..i],               // This should be our version str "0.5.11"
+        }
```
Comment (SteveLauC) [inline src/steps/generic.rs:1335]:
```suggestion
        // Remove the tailing part " (c4d0caaee 2024-12-19)\n", if it's there
        match start_trimmed.find(' ') {
            None => start_trimmed.trim_end_matches('\n'), // Otherwise, just strip the newline
            Some(i) => &start_trimmed[..i],
        }
        
        // After trimming, it should be a string in 2 possible formats, both can be handled by `Version::parse()`
        //
        // 1. "0.5.11"
        // 2. "0.5.11+1"
```

**Review by SteveLauC — APPROVED** [review]
Thanks!
